# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cs_protoid_pb2 as cs__protoid__pb2
import ss_protoid_pb2 as ss__protoid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='ProtoMsg',
  syntax='proto3',
  serialized_pb=_b('\n\nbase.proto\x12\x08ProtoMsg\x1a\x10\x63s_protoid.proto\x1a\x10ss_protoid.proto\"(\n\x03Ret\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[cs__protoid__pb2.DESCRIPTOR,ss__protoid__pb2.DESCRIPTOR,])




_RET = _descriptor.Descriptor(
  name='Ret',
  full_name='ProtoMsg.Ret',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='ProtoMsg.Ret.err_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='ProtoMsg.Ret.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['Ret'] = _RET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ret = _reflection.GeneratedProtocolMessageType('Ret', (_message.Message,), dict(
  DESCRIPTOR = _RET,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.Ret)
  ))
_sym_db.RegisterMessage(Ret)


# @@protoc_insertion_point(module_scope)
