# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base_news.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base_news.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x62\x61se_news.proto\x12\nQuoteProto\"\x98\x01\n\x08\x42\x61seHead\x12\x0e\n\x06req_ID\x18\x01 \x02(\x04\x12\x10\n\x08pack_len\x18\x02 \x02(\x03\x12(\n\x07\x63md_set\x18\x03 \x02(\x0e\x32\x17.QuoteProto.EnumCmdType\x12\x0f\n\x07seq_set\x18\x04 \x02(\x03\x12\x0b\n\x03UID\x18\x05 \x02(\x05\x12\x0f\n\x07version\x18\x06 \x02(\t\x12\x11\n\tsafe_flag\x18\x07 \x01(\x05\"\x1c\n\x08\x42\x61seBody\x12\x10\n\x08msg_data\x18\x01 \x01(\x0c\"Q\n\x07\x42\x61seMsg\x12\"\n\x04head\x18\x01 \x02(\x0b\x32\x14.QuoteProto.BaseHead\x12\"\n\x04\x62ody\x18\x02 \x02(\x0b\x32\x14.QuoteProto.BaseBody*+\n\x0b\x45numCmdType\x12\x0f\n\x0blogin_sever\x10\x01\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x02')
)

_ENUMCMDTYPE = _descriptor.EnumDescriptor(
  name='EnumCmdType',
  full_name='QuoteProto.EnumCmdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='login_sever', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=299,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_ENUMCMDTYPE)

EnumCmdType = enum_type_wrapper.EnumTypeWrapper(_ENUMCMDTYPE)
login_sever = 1
DEFAULT = 2



_BASEHEAD = _descriptor.Descriptor(
  name='BaseHead',
  full_name='QuoteProto.BaseHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_ID', full_name='QuoteProto.BaseHead.req_ID', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pack_len', full_name='QuoteProto.BaseHead.pack_len', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmd_set', full_name='QuoteProto.BaseHead.cmd_set', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq_set', full_name='QuoteProto.BaseHead.seq_set', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UID', full_name='QuoteProto.BaseHead.UID', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='QuoteProto.BaseHead.version', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='safe_flag', full_name='QuoteProto.BaseHead.safe_flag', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=184,
)


_BASEBODY = _descriptor.Descriptor(
  name='BaseBody',
  full_name='QuoteProto.BaseBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_data', full_name='QuoteProto.BaseBody.msg_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=214,
)


_BASEMSG = _descriptor.Descriptor(
  name='BaseMsg',
  full_name='QuoteProto.BaseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='head', full_name='QuoteProto.BaseMsg.head', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='QuoteProto.BaseMsg.body', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=297,
)

_BASEHEAD.fields_by_name['cmd_set'].enum_type = _ENUMCMDTYPE
_BASEMSG.fields_by_name['head'].message_type = _BASEHEAD
_BASEMSG.fields_by_name['body'].message_type = _BASEBODY
DESCRIPTOR.message_types_by_name['BaseHead'] = _BASEHEAD
DESCRIPTOR.message_types_by_name['BaseBody'] = _BASEBODY
DESCRIPTOR.message_types_by_name['BaseMsg'] = _BASEMSG
DESCRIPTOR.enum_types_by_name['EnumCmdType'] = _ENUMCMDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseHead = _reflection.GeneratedProtocolMessageType('BaseHead', (_message.Message,), dict(
  DESCRIPTOR = _BASEHEAD,
  __module__ = 'base_news_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.BaseHead)
  ))
_sym_db.RegisterMessage(BaseHead)

BaseBody = _reflection.GeneratedProtocolMessageType('BaseBody', (_message.Message,), dict(
  DESCRIPTOR = _BASEBODY,
  __module__ = 'base_news_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.BaseBody)
  ))
_sym_db.RegisterMessage(BaseBody)

BaseMsg = _reflection.GeneratedProtocolMessageType('BaseMsg', (_message.Message,), dict(
  DESCRIPTOR = _BASEMSG,
  __module__ = 'base_news_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.BaseMsg)
  ))
_sym_db.RegisterMessage(BaseMsg)


# @@protoc_insertion_point(module_scope)
