# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadcast.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ret_base_pb2 as ret__base__pb2
import public_message_pb2 as public__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='broadcast.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x62roadcast.proto\x12\nQuoteProto\x1a\x0eret_base.proto\x1a\x14public_message.proto\"=\n\x14\x42roadCastTradeDayMsg\x12\x11\n\ttrade_day\x18\x01 \x01(\x05\x12\x12\n\ntrade_type\x18\x02 \x01(\x05')
  ,
  dependencies=[ret__base__pb2.DESCRIPTOR,public__message__pb2.DESCRIPTOR,])




_BROADCASTTRADEDAYMSG = _descriptor.Descriptor(
  name='BroadCastTradeDayMsg',
  full_name='QuoteProto.BroadCastTradeDayMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trade_day', full_name='QuoteProto.BroadCastTradeDayMsg.trade_day', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trade_type', full_name='QuoteProto.BroadCastTradeDayMsg.trade_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['BroadCastTradeDayMsg'] = _BROADCASTTRADEDAYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BroadCastTradeDayMsg = _reflection.GeneratedProtocolMessageType('BroadCastTradeDayMsg', (_message.Message,), dict(
  DESCRIPTOR = _BROADCASTTRADEDAYMSG,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.BroadCastTradeDayMsg)
  ))
_sym_db.RegisterMessage(BroadCastTradeDayMsg)


# @@protoc_insertion_point(module_scope)
