# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2
import cs_protoid_pb2 as cs__protoid__pb2
import ss_protoid_pb2 as ss__protoid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cluster.proto',
  package='ProtoMsg',
  syntax='proto3',
  serialized_pb=_b('\n\rcluster.proto\x12\x08ProtoMsg\x1a\nbase.proto\x1a\x10\x63s_protoid.proto\x1a\x10ss_protoid.proto\"\xac\x02\n\rPbSvrBaseInfo\x12\x10\n\x08group_id\x18\x01 \x01(\x05\x12\x0e\n\x06svr_id\x18\x02 \x01(\x05\x12%\n\x08svr_type\x18\x03 \x01(\x0e\x32\x13.ProtoMsg.emSvrType\x12\x0c\n\x04\x61\x64\x64r\x18\x04 \x01(\t\x12\x0b\n\x03ttl\x18\x05 \x01(\x05\x12\x0f\n\x07timeout\x18\x06 \x01(\x05\x12)\n\x0c\x63s_msg_begin\x18\x07 \x01(\x0e\x32\x13.ProtoMsg.emCSMsgId\x12\'\n\ncs_msg_end\x18\x08 \x01(\x0e\x32\x13.ProtoMsg.emCSMsgId\x12)\n\x0css_msg_begin\x18\t \x01(\x0e\x32\x13.ProtoMsg.emSSMsgId\x12\'\n\nss_msg_end\x18\n \x01(\x0e\x32\x13.ProtoMsg.emSSMsgId\"o\n\x1aPbSvrRegisterClusterReqMsg\x12)\n\x08svr_info\x18\x01 \x01(\x0b\x32\x17.ProtoMsg.PbSvrBaseInfo\x12&\n\tsvr_types\x18\x02 \x03(\x0e\x32\x13.ProtoMsg.emSvrType\"_\n\x1aPbSvrRegisterClusterResMsg\x12\x1a\n\x03ret\x18\x01 \x01(\x0b\x32\r.ProtoMsg.Ret\x12%\n\x04svrs\x18\x02 \x03(\x0b\x32\x17.ProtoMsg.PbSvrBaseInfo\"o\n\x14PbSvrBroadClusterMsg\x12,\n\x08opr_type\x18\x01 \x01(\x0e\x32\x1a.ProtoMsg.emClusterOprType\x12)\n\x08svr_info\x18\x02 \x01(\x0b\x32\x17.ProtoMsg.PbSvrBaseInfo*b\n\temSvrType\x12\x0e\n\nST_Invalid\x10\x00\x12\x08\n\x04Gate\x10\x01\x12\x06\n\x02Gs\x10\x02\x12\t\n\x05World\x10\x03\x12\t\n\x05Login\x10\x04\x12\x08\n\x04\x43hat\x10\x05\x12\x06\n\x02\x44\x42\x10\x06\x12\x0b\n\x07\x43luster\x10\x07*5\n\x10\x65mClusterOprType\x12\x0f\n\x0b\x43OT_Invalid\x10\x00\x12\x07\n\x03\x41\x64\x64\x10\x01\x12\x07\n\x03\x44\x65l\x10\x02\x62\x06proto3')
  ,
  dependencies=[base__pb2.DESCRIPTOR,cs__protoid__pb2.DESCRIPTOR,ss__protoid__pb2.DESCRIPTOR,])

_EMSVRTYPE = _descriptor.EnumDescriptor(
  name='emSvrType',
  full_name='ProtoMsg.emSvrType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ST_Invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Gate', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Gs', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='World', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Login', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Chat', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DB', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Cluster', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=701,
  serialized_end=799,
)
_sym_db.RegisterEnumDescriptor(_EMSVRTYPE)

emSvrType = enum_type_wrapper.EnumTypeWrapper(_EMSVRTYPE)
_EMCLUSTEROPRTYPE = _descriptor.EnumDescriptor(
  name='emClusterOprType',
  full_name='ProtoMsg.emClusterOprType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COT_Invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Add', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Del', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=801,
  serialized_end=854,
)
_sym_db.RegisterEnumDescriptor(_EMCLUSTEROPRTYPE)

emClusterOprType = enum_type_wrapper.EnumTypeWrapper(_EMCLUSTEROPRTYPE)
ST_Invalid = 0
Gate = 1
Gs = 2
World = 3
Login = 4
Chat = 5
DB = 6
Cluster = 7
COT_Invalid = 0
Add = 1
Del = 2



_PBSVRBASEINFO = _descriptor.Descriptor(
  name='PbSvrBaseInfo',
  full_name='ProtoMsg.PbSvrBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='ProtoMsg.PbSvrBaseInfo.group_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='svr_id', full_name='ProtoMsg.PbSvrBaseInfo.svr_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='svr_type', full_name='ProtoMsg.PbSvrBaseInfo.svr_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='ProtoMsg.PbSvrBaseInfo.addr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='ProtoMsg.PbSvrBaseInfo.ttl', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='ProtoMsg.PbSvrBaseInfo.timeout', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cs_msg_begin', full_name='ProtoMsg.PbSvrBaseInfo.cs_msg_begin', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cs_msg_end', full_name='ProtoMsg.PbSvrBaseInfo.cs_msg_end', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ss_msg_begin', full_name='ProtoMsg.PbSvrBaseInfo.ss_msg_begin', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ss_msg_end', full_name='ProtoMsg.PbSvrBaseInfo.ss_msg_end', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=376,
)


_PBSVRREGISTERCLUSTERREQMSG = _descriptor.Descriptor(
  name='PbSvrRegisterClusterReqMsg',
  full_name='ProtoMsg.PbSvrRegisterClusterReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svr_info', full_name='ProtoMsg.PbSvrRegisterClusterReqMsg.svr_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='svr_types', full_name='ProtoMsg.PbSvrRegisterClusterReqMsg.svr_types', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=489,
)


_PBSVRREGISTERCLUSTERRESMSG = _descriptor.Descriptor(
  name='PbSvrRegisterClusterResMsg',
  full_name='ProtoMsg.PbSvrRegisterClusterResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoMsg.PbSvrRegisterClusterResMsg.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='svrs', full_name='ProtoMsg.PbSvrRegisterClusterResMsg.svrs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=586,
)


_PBSVRBROADCLUSTERMSG = _descriptor.Descriptor(
  name='PbSvrBroadClusterMsg',
  full_name='ProtoMsg.PbSvrBroadClusterMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opr_type', full_name='ProtoMsg.PbSvrBroadClusterMsg.opr_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='svr_info', full_name='ProtoMsg.PbSvrBroadClusterMsg.svr_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=588,
  serialized_end=699,
)

_PBSVRBASEINFO.fields_by_name['svr_type'].enum_type = _EMSVRTYPE
_PBSVRBASEINFO.fields_by_name['cs_msg_begin'].enum_type = cs__protoid__pb2._EMCSMSGID
_PBSVRBASEINFO.fields_by_name['cs_msg_end'].enum_type = cs__protoid__pb2._EMCSMSGID
_PBSVRBASEINFO.fields_by_name['ss_msg_begin'].enum_type = ss__protoid__pb2._EMSSMSGID
_PBSVRBASEINFO.fields_by_name['ss_msg_end'].enum_type = ss__protoid__pb2._EMSSMSGID
_PBSVRREGISTERCLUSTERREQMSG.fields_by_name['svr_info'].message_type = _PBSVRBASEINFO
_PBSVRREGISTERCLUSTERREQMSG.fields_by_name['svr_types'].enum_type = _EMSVRTYPE
_PBSVRREGISTERCLUSTERRESMSG.fields_by_name['ret'].message_type = base__pb2._RET
_PBSVRREGISTERCLUSTERRESMSG.fields_by_name['svrs'].message_type = _PBSVRBASEINFO
_PBSVRBROADCLUSTERMSG.fields_by_name['opr_type'].enum_type = _EMCLUSTEROPRTYPE
_PBSVRBROADCLUSTERMSG.fields_by_name['svr_info'].message_type = _PBSVRBASEINFO
DESCRIPTOR.message_types_by_name['PbSvrBaseInfo'] = _PBSVRBASEINFO
DESCRIPTOR.message_types_by_name['PbSvrRegisterClusterReqMsg'] = _PBSVRREGISTERCLUSTERREQMSG
DESCRIPTOR.message_types_by_name['PbSvrRegisterClusterResMsg'] = _PBSVRREGISTERCLUSTERRESMSG
DESCRIPTOR.message_types_by_name['PbSvrBroadClusterMsg'] = _PBSVRBROADCLUSTERMSG
DESCRIPTOR.enum_types_by_name['emSvrType'] = _EMSVRTYPE
DESCRIPTOR.enum_types_by_name['emClusterOprType'] = _EMCLUSTEROPRTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbSvrBaseInfo = _reflection.GeneratedProtocolMessageType('PbSvrBaseInfo', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRBASEINFO,
  __module__ = 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrBaseInfo)
  ))
_sym_db.RegisterMessage(PbSvrBaseInfo)

PbSvrRegisterClusterReqMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterClusterReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERCLUSTERREQMSG,
  __module__ = 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterClusterReqMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterClusterReqMsg)

PbSvrRegisterClusterResMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterClusterResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERCLUSTERRESMSG,
  __module__ = 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterClusterResMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterClusterResMsg)

PbSvrBroadClusterMsg = _reflection.GeneratedProtocolMessageType('PbSvrBroadClusterMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRBROADCLUSTERMSG,
  __module__ = 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrBroadClusterMsg)
  ))
_sym_db.RegisterMessage(PbSvrBroadClusterMsg)


# @@protoc_insertion_point(module_scope)
