# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs_protoid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs_protoid.proto',
  package='ProtoMsg',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63s_protoid.proto\x12\x08ProtoMsg*\xd9\x01\n\temCSMsgId\x12\x12\n\x0e\x43S_MSG_INVALID\x10\x00\x12\x15\n\x11\x43S_MSG_HEART_BEAT\x10\x01\x12\x12\n\x0c\x43S_MSG_BEGIN\x10\xa0\x8d\x06\x12\x19\n\x13\x43S_MSG_PLAYER_LOGIN\x10\xa1\x8d\x06\x12\x18\n\x12\x43S_MSG_PLAYER_BIND\x10\xa2\x8d\x06\x12\x16\n\x10\x43S_MSG_LOGIN_END\x10\xaf\xdb\x06\x12\x17\n\x11\x43S_MSG_GAME_BEGIN\x10\xb0\xdb\x06\x12\x15\n\x0f\x43S_MSG_GAME_END\x10\xbf\xa9\x07\x12\x10\n\nCS_MSG_END\x10\xbf\x9a\x0c\x62\x06proto3')
)

_EMCSMSGID = _descriptor.EnumDescriptor(
  name='emCSMsgId',
  full_name='ProtoMsg.emCSMsgId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CS_MSG_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CS_MSG_HEART_BEAT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CS_MSG_BEGIN', index=2, number=100000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CS_MSG_PLAYER_LOGIN', index=3, number=100001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CS_MSG_PLAYER_BIND', index=4, number=100002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CS_MSG_LOGIN_END', index=5, number=109999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CS_MSG_GAME_BEGIN', index=6, number=110000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CS_MSG_GAME_END', index=7, number=119999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CS_MSG_END', index=8, number=199999,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=31,
  serialized_end=248,
)
_sym_db.RegisterEnumDescriptor(_EMCSMSGID)

emCSMsgId = enum_type_wrapper.EnumTypeWrapper(_EMCSMSGID)
CS_MSG_INVALID = 0
CS_MSG_HEART_BEAT = 1
CS_MSG_BEGIN = 100000
CS_MSG_PLAYER_LOGIN = 100001
CS_MSG_PLAYER_BIND = 100002
CS_MSG_LOGIN_END = 109999
CS_MSG_GAME_BEGIN = 110000
CS_MSG_GAME_END = 119999
CS_MSG_END = 199999


DESCRIPTOR.enum_types_by_name['emCSMsgId'] = _EMCSMSGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
