# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cluster_pb2 as cluster__pb2
import base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='db.proto',
  package='ProtoMsg',
  syntax='proto3',
  serialized_pb=_b('\n\x08\x64\x62.proto\x12\x08ProtoMsg\x1a\rcluster.proto\x1a\nbase.proto\"B\n\x15PbSvrRegisterDBReqMsg\x12)\n\x08svr_info\x18\x01 \x01(\x0b\x32\x17.ProtoMsg.PbSvrBaseInfo\"3\n\x15PbSvrRegisterDBResMsg\x12\x1a\n\x03ret\x18\x01 \x01(\x0b\x32\r.ProtoMsg.Ret\"f\n\x14PbSvrDBServiceReqMsg\x12&\n\tdb_engine\x18\x01 \x01(\x0e\x32\x13.ProtoMsg.emDBEngin\x12\x14\n\x0creq_msg_name\x18\x02 \x01(\t\x12\x10\n\x08req_data\x18\x03 \x01(\t\"\x82\x01\n\x14PbSvrDBServiceResMsg\x12\x1a\n\x03ret\x18\x01 \x01(\x0b\x32\r.ProtoMsg.Ret\x12&\n\tdb_engine\x18\x02 \x01(\x0e\x32\x13.ProtoMsg.emDBEngin\x12\x14\n\x0cres_msg_name\x18\x03 \x01(\t\x12\x10\n\x08res_data\x18\x04 \x01(\t\"1\n\x15PbSvrDBTestRecvReqMsg\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"1\n\x15PbSvrDBTestRecvResMsg\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t*L\n\temDBEngin\x12\x15\n\x11\x44\x42_engine_invalid\x10\x00\x12\x13\n\x0f\x44\x42_engine_redis\x10\x01\x12\x13\n\x0f\x44\x42_engine_mysql\x10\x02\x62\x06proto3')
  ,
  dependencies=[cluster__pb2.DESCRIPTOR,base__pb2.DESCRIPTOR,])

_EMDBENGIN = _descriptor.EnumDescriptor(
  name='emDBEngin',
  full_name='ProtoMsg.emDBEngin',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DB_engine_invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DB_engine_redis', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DB_engine_mysql', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=509,
  serialized_end=585,
)
_sym_db.RegisterEnumDescriptor(_EMDBENGIN)

emDBEngin = enum_type_wrapper.EnumTypeWrapper(_EMDBENGIN)
DB_engine_invalid = 0
DB_engine_redis = 1
DB_engine_mysql = 2



_PBSVRREGISTERDBREQMSG = _descriptor.Descriptor(
  name='PbSvrRegisterDBReqMsg',
  full_name='ProtoMsg.PbSvrRegisterDBReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svr_info', full_name='ProtoMsg.PbSvrRegisterDBReqMsg.svr_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=115,
)


_PBSVRREGISTERDBRESMSG = _descriptor.Descriptor(
  name='PbSvrRegisterDBResMsg',
  full_name='ProtoMsg.PbSvrRegisterDBResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoMsg.PbSvrRegisterDBResMsg.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=168,
)


_PBSVRDBSERVICEREQMSG = _descriptor.Descriptor(
  name='PbSvrDBServiceReqMsg',
  full_name='ProtoMsg.PbSvrDBServiceReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='db_engine', full_name='ProtoMsg.PbSvrDBServiceReqMsg.db_engine', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_msg_name', full_name='ProtoMsg.PbSvrDBServiceReqMsg.req_msg_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_data', full_name='ProtoMsg.PbSvrDBServiceReqMsg.req_data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=272,
)


_PBSVRDBSERVICERESMSG = _descriptor.Descriptor(
  name='PbSvrDBServiceResMsg',
  full_name='ProtoMsg.PbSvrDBServiceResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoMsg.PbSvrDBServiceResMsg.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='db_engine', full_name='ProtoMsg.PbSvrDBServiceResMsg.db_engine', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='res_msg_name', full_name='ProtoMsg.PbSvrDBServiceResMsg.res_msg_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='res_data', full_name='ProtoMsg.PbSvrDBServiceResMsg.res_data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=405,
)


_PBSVRDBTESTRECVREQMSG = _descriptor.Descriptor(
  name='PbSvrDBTestRecvReqMsg',
  full_name='ProtoMsg.PbSvrDBTestRecvReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtoMsg.PbSvrDBTestRecvReqMsg.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ProtoMsg.PbSvrDBTestRecvReqMsg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=456,
)


_PBSVRDBTESTRECVRESMSG = _descriptor.Descriptor(
  name='PbSvrDBTestRecvResMsg',
  full_name='ProtoMsg.PbSvrDBTestRecvResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtoMsg.PbSvrDBTestRecvResMsg.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ProtoMsg.PbSvrDBTestRecvResMsg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=507,
)

_PBSVRREGISTERDBREQMSG.fields_by_name['svr_info'].message_type = cluster__pb2._PBSVRBASEINFO
_PBSVRREGISTERDBRESMSG.fields_by_name['ret'].message_type = base__pb2._RET
_PBSVRDBSERVICEREQMSG.fields_by_name['db_engine'].enum_type = _EMDBENGIN
_PBSVRDBSERVICERESMSG.fields_by_name['ret'].message_type = base__pb2._RET
_PBSVRDBSERVICERESMSG.fields_by_name['db_engine'].enum_type = _EMDBENGIN
DESCRIPTOR.message_types_by_name['PbSvrRegisterDBReqMsg'] = _PBSVRREGISTERDBREQMSG
DESCRIPTOR.message_types_by_name['PbSvrRegisterDBResMsg'] = _PBSVRREGISTERDBRESMSG
DESCRIPTOR.message_types_by_name['PbSvrDBServiceReqMsg'] = _PBSVRDBSERVICEREQMSG
DESCRIPTOR.message_types_by_name['PbSvrDBServiceResMsg'] = _PBSVRDBSERVICERESMSG
DESCRIPTOR.message_types_by_name['PbSvrDBTestRecvReqMsg'] = _PBSVRDBTESTRECVREQMSG
DESCRIPTOR.message_types_by_name['PbSvrDBTestRecvResMsg'] = _PBSVRDBTESTRECVRESMSG
DESCRIPTOR.enum_types_by_name['emDBEngin'] = _EMDBENGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbSvrRegisterDBReqMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterDBReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERDBREQMSG,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterDBReqMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterDBReqMsg)

PbSvrRegisterDBResMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterDBResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERDBRESMSG,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterDBResMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterDBResMsg)

PbSvrDBServiceReqMsg = _reflection.GeneratedProtocolMessageType('PbSvrDBServiceReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRDBSERVICEREQMSG,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrDBServiceReqMsg)
  ))
_sym_db.RegisterMessage(PbSvrDBServiceReqMsg)

PbSvrDBServiceResMsg = _reflection.GeneratedProtocolMessageType('PbSvrDBServiceResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRDBSERVICERESMSG,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrDBServiceResMsg)
  ))
_sym_db.RegisterMessage(PbSvrDBServiceResMsg)

PbSvrDBTestRecvReqMsg = _reflection.GeneratedProtocolMessageType('PbSvrDBTestRecvReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRDBTESTRECVREQMSG,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrDBTestRecvReqMsg)
  ))
_sym_db.RegisterMessage(PbSvrDBTestRecvReqMsg)

PbSvrDBTestRecvResMsg = _reflection.GeneratedProtocolMessageType('PbSvrDBTestRecvResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRDBTESTRECVRESMSG,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrDBTestRecvResMsg)
  ))
_sym_db.RegisterMessage(PbSvrDBTestRecvResMsg)


# @@protoc_insertion_point(module_scope)
