# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cluster_pb2 as cluster__pb2
import base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='ProtoMsg',
  syntax='proto3',
  serialized_pb=_b('\n\ngame.proto\x12\x08ProtoMsg\x1a\rcluster.proto\x1a\nbase.proto\"D\n\x17PbSvrRegisterGameReqMsg\x12)\n\x08svr_info\x18\x01 \x01(\x0b\x32\x17.ProtoMsg.PbSvrBaseInfo\"5\n\x17PbSvrRegisterGameResMsg\x12\x1a\n\x03ret\x18\x01 \x01(\x0b\x32\r.ProtoMsg.Ret\"3\n\x14PbSvrGameLoginReqMsg\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12\x0e\n\x06online\x18\x02 \x01(\x08\"?\n\x14PbSvrGameLoginResMsg\x12\x1a\n\x03ret\x18\x01 \x01(\x0b\x32\r.ProtoMsg.Ret\x12\x0b\n\x03uid\x18\x02 \x01(\x04\x62\x06proto3')
  ,
  dependencies=[cluster__pb2.DESCRIPTOR,base__pb2.DESCRIPTOR,])




_PBSVRREGISTERGAMEREQMSG = _descriptor.Descriptor(
  name='PbSvrRegisterGameReqMsg',
  full_name='ProtoMsg.PbSvrRegisterGameReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svr_info', full_name='ProtoMsg.PbSvrRegisterGameReqMsg.svr_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=119,
)


_PBSVRREGISTERGAMERESMSG = _descriptor.Descriptor(
  name='PbSvrRegisterGameResMsg',
  full_name='ProtoMsg.PbSvrRegisterGameResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoMsg.PbSvrRegisterGameResMsg.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=174,
)


_PBSVRGAMELOGINREQMSG = _descriptor.Descriptor(
  name='PbSvrGameLoginReqMsg',
  full_name='ProtoMsg.PbSvrGameLoginReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ProtoMsg.PbSvrGameLoginReqMsg.uid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='online', full_name='ProtoMsg.PbSvrGameLoginReqMsg.online', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=227,
)


_PBSVRGAMELOGINRESMSG = _descriptor.Descriptor(
  name='PbSvrGameLoginResMsg',
  full_name='ProtoMsg.PbSvrGameLoginResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoMsg.PbSvrGameLoginResMsg.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='ProtoMsg.PbSvrGameLoginResMsg.uid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=292,
)

_PBSVRREGISTERGAMEREQMSG.fields_by_name['svr_info'].message_type = cluster__pb2._PBSVRBASEINFO
_PBSVRREGISTERGAMERESMSG.fields_by_name['ret'].message_type = base__pb2._RET
_PBSVRGAMELOGINRESMSG.fields_by_name['ret'].message_type = base__pb2._RET
DESCRIPTOR.message_types_by_name['PbSvrRegisterGameReqMsg'] = _PBSVRREGISTERGAMEREQMSG
DESCRIPTOR.message_types_by_name['PbSvrRegisterGameResMsg'] = _PBSVRREGISTERGAMERESMSG
DESCRIPTOR.message_types_by_name['PbSvrGameLoginReqMsg'] = _PBSVRGAMELOGINREQMSG
DESCRIPTOR.message_types_by_name['PbSvrGameLoginResMsg'] = _PBSVRGAMELOGINRESMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbSvrRegisterGameReqMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterGameReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERGAMEREQMSG,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterGameReqMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterGameReqMsg)

PbSvrRegisterGameResMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterGameResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERGAMERESMSG,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterGameResMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterGameResMsg)

PbSvrGameLoginReqMsg = _reflection.GeneratedProtocolMessageType('PbSvrGameLoginReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRGAMELOGINREQMSG,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrGameLoginReqMsg)
  ))
_sym_db.RegisterMessage(PbSvrGameLoginReqMsg)

PbSvrGameLoginResMsg = _reflection.GeneratedProtocolMessageType('PbSvrGameLoginResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRGAMELOGINRESMSG,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrGameLoginResMsg)
  ))
_sym_db.RegisterMessage(PbSvrGameLoginResMsg)


# @@protoc_insertion_point(module_scope)
