# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inner_svr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import public_message_pb2 as public__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='inner_svr.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x0finner_svr.proto\x12\nQuoteProto\x1a\x14public_message.proto\"E\n\x12QuoteBaseStockInfo\x12/\n\x0b\x63odes_table\x18\x01 \x03(\x0b\x32\x1a.QuoteProto.StockCodeTable\"5\n\x0eQuoteInfoArray\x12#\n\x05table\x18\x01 \x03(\x0b\x32\x14.QuoteProto.StockMsg\"5\n\x0e\x42lockInfoArray\x12#\n\x05table\x18\x01 \x03(\x0b\x32\x14.QuoteProto.BlockMsg\"5\n\x0eMoneyInfoArray\x12#\n\x05table\x18\x01 \x03(\x0b\x32\x14.QuoteProto.MoneyMsg\"8\n\x0eKlineInfoArray\x12&\n\x05table\x18\x01 \x03(\x0b\x32\x17.QuoteProto.PeriodKLine')
  ,
  dependencies=[public__message__pb2.DESCRIPTOR,])




_QUOTEBASESTOCKINFO = _descriptor.Descriptor(
  name='QuoteBaseStockInfo',
  full_name='QuoteProto.QuoteBaseStockInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codes_table', full_name='QuoteProto.QuoteBaseStockInfo.codes_table', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=122,
)


_QUOTEINFOARRAY = _descriptor.Descriptor(
  name='QuoteInfoArray',
  full_name='QuoteProto.QuoteInfoArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='QuoteProto.QuoteInfoArray.table', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=177,
)


_BLOCKINFOARRAY = _descriptor.Descriptor(
  name='BlockInfoArray',
  full_name='QuoteProto.BlockInfoArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='QuoteProto.BlockInfoArray.table', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=232,
)


_MONEYINFOARRAY = _descriptor.Descriptor(
  name='MoneyInfoArray',
  full_name='QuoteProto.MoneyInfoArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='QuoteProto.MoneyInfoArray.table', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=287,
)


_KLINEINFOARRAY = _descriptor.Descriptor(
  name='KlineInfoArray',
  full_name='QuoteProto.KlineInfoArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='QuoteProto.KlineInfoArray.table', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=345,
)

_QUOTEBASESTOCKINFO.fields_by_name['codes_table'].message_type = public__message__pb2._STOCKCODETABLE
_QUOTEINFOARRAY.fields_by_name['table'].message_type = public__message__pb2._STOCKMSG
_BLOCKINFOARRAY.fields_by_name['table'].message_type = public__message__pb2._BLOCKMSG
_MONEYINFOARRAY.fields_by_name['table'].message_type = public__message__pb2._MONEYMSG
_KLINEINFOARRAY.fields_by_name['table'].message_type = public__message__pb2._PERIODKLINE
DESCRIPTOR.message_types_by_name['QuoteBaseStockInfo'] = _QUOTEBASESTOCKINFO
DESCRIPTOR.message_types_by_name['QuoteInfoArray'] = _QUOTEINFOARRAY
DESCRIPTOR.message_types_by_name['BlockInfoArray'] = _BLOCKINFOARRAY
DESCRIPTOR.message_types_by_name['MoneyInfoArray'] = _MONEYINFOARRAY
DESCRIPTOR.message_types_by_name['KlineInfoArray'] = _KLINEINFOARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuoteBaseStockInfo = _reflection.GeneratedProtocolMessageType('QuoteBaseStockInfo', (_message.Message,), dict(
  DESCRIPTOR = _QUOTEBASESTOCKINFO,
  __module__ = 'inner_svr_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.QuoteBaseStockInfo)
  ))
_sym_db.RegisterMessage(QuoteBaseStockInfo)

QuoteInfoArray = _reflection.GeneratedProtocolMessageType('QuoteInfoArray', (_message.Message,), dict(
  DESCRIPTOR = _QUOTEINFOARRAY,
  __module__ = 'inner_svr_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.QuoteInfoArray)
  ))
_sym_db.RegisterMessage(QuoteInfoArray)

BlockInfoArray = _reflection.GeneratedProtocolMessageType('BlockInfoArray', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKINFOARRAY,
  __module__ = 'inner_svr_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.BlockInfoArray)
  ))
_sym_db.RegisterMessage(BlockInfoArray)

MoneyInfoArray = _reflection.GeneratedProtocolMessageType('MoneyInfoArray', (_message.Message,), dict(
  DESCRIPTOR = _MONEYINFOARRAY,
  __module__ = 'inner_svr_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.MoneyInfoArray)
  ))
_sym_db.RegisterMessage(MoneyInfoArray)

KlineInfoArray = _reflection.GeneratedProtocolMessageType('KlineInfoArray', (_message.Message,), dict(
  DESCRIPTOR = _KLINEINFOARRAY,
  __module__ = 'inner_svr_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.KlineInfoArray)
  ))
_sym_db.RegisterMessage(KlineInfoArray)


# @@protoc_insertion_point(module_scope)
