# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ret_base_pb2 as ret__base__pb2
import public_message_pb2 as public__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kline.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x0bkline.proto\x12\nQuoteProto\x1a\x0eret_base.proto\x1a\x14public_message.proto\"m\n\x0fGetKLineRequest\x12\x12\n\nstock_name\x18\x01 \x02(\t\x12\x12\n\nkline_type\x18\x02 \x02(\x05\x12\x12\n\nstart_time\x18\x03 \x02(\x05\x12\r\n\x05\x63ount\x18\x04 \x02(\x05\x12\x0f\n\x07is_desc\x18\x05 \x02(\x08\"\x7f\n\x10GetKLineResponse\x12\x1c\n\x03ret\x18\x01 \x02(\x0b\x32\x0f.QuoteProto.Ret\x12%\n\nkline_info\x18\x02 \x03(\x0b\x32\x11.QuoteProto.KLine\x12\x12\n\nstock_code\x18\x03 \x01(\t\x12\x12\n\nkline_type\x18\x04 \x01(\x05\"=\n\x13GetTimeKLineRequest\x12\x12\n\nstock_name\x18\x01 \x02(\t\x12\x12\n\nstart_time\x18\x02 \x02(\x05\"\x83\x01\n\x14GetTimeKLineResponse\x12\x1c\n\x03ret\x18\x01 \x02(\x0b\x32\x0f.QuoteProto.Ret\x12%\n\nkline_info\x18\x02 \x03(\x0b\x32\x11.QuoteProto.KLine\x12\x12\n\nstock_code\x18\x03 \x01(\t\x12\x12\n\nkline_type\x18\x04 \x01(\x05')
  ,
  dependencies=[ret__base__pb2.DESCRIPTOR,public__message__pb2.DESCRIPTOR,])




_GETKLINEREQUEST = _descriptor.Descriptor(
  name='GetKLineRequest',
  full_name='QuoteProto.GetKLineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_name', full_name='QuoteProto.GetKLineRequest.stock_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kline_type', full_name='QuoteProto.GetKLineRequest.kline_type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='QuoteProto.GetKLineRequest.start_time', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='QuoteProto.GetKLineRequest.count', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_desc', full_name='QuoteProto.GetKLineRequest.is_desc', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=174,
)


_GETKLINERESPONSE = _descriptor.Descriptor(
  name='GetKLineResponse',
  full_name='QuoteProto.GetKLineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.GetKLineResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kline_info', full_name='QuoteProto.GetKLineResponse.kline_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='QuoteProto.GetKLineResponse.stock_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kline_type', full_name='QuoteProto.GetKLineResponse.kline_type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=303,
)


_GETTIMEKLINEREQUEST = _descriptor.Descriptor(
  name='GetTimeKLineRequest',
  full_name='QuoteProto.GetTimeKLineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_name', full_name='QuoteProto.GetTimeKLineRequest.stock_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='QuoteProto.GetTimeKLineRequest.start_time', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=366,
)


_GETTIMEKLINERESPONSE = _descriptor.Descriptor(
  name='GetTimeKLineResponse',
  full_name='QuoteProto.GetTimeKLineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.GetTimeKLineResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kline_info', full_name='QuoteProto.GetTimeKLineResponse.kline_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='QuoteProto.GetTimeKLineResponse.stock_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kline_type', full_name='QuoteProto.GetTimeKLineResponse.kline_type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=500,
)

_GETKLINERESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_GETKLINERESPONSE.fields_by_name['kline_info'].message_type = public__message__pb2._KLINE
_GETTIMEKLINERESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_GETTIMEKLINERESPONSE.fields_by_name['kline_info'].message_type = public__message__pb2._KLINE
DESCRIPTOR.message_types_by_name['GetKLineRequest'] = _GETKLINEREQUEST
DESCRIPTOR.message_types_by_name['GetKLineResponse'] = _GETKLINERESPONSE
DESCRIPTOR.message_types_by_name['GetTimeKLineRequest'] = _GETTIMEKLINEREQUEST
DESCRIPTOR.message_types_by_name['GetTimeKLineResponse'] = _GETTIMEKLINERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetKLineRequest = _reflection.GeneratedProtocolMessageType('GetKLineRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETKLINEREQUEST,
  __module__ = 'kline_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.GetKLineRequest)
  ))
_sym_db.RegisterMessage(GetKLineRequest)

GetKLineResponse = _reflection.GeneratedProtocolMessageType('GetKLineResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETKLINERESPONSE,
  __module__ = 'kline_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.GetKLineResponse)
  ))
_sym_db.RegisterMessage(GetKLineResponse)

GetTimeKLineRequest = _reflection.GeneratedProtocolMessageType('GetTimeKLineRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTIMEKLINEREQUEST,
  __module__ = 'kline_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.GetTimeKLineRequest)
  ))
_sym_db.RegisterMessage(GetTimeKLineRequest)

GetTimeKLineResponse = _reflection.GeneratedProtocolMessageType('GetTimeKLineResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETTIMEKLINERESPONSE,
  __module__ = 'kline_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.GetTimeKLineResponse)
  ))
_sym_db.RegisterMessage(GetTimeKLineResponse)


# @@protoc_insertion_point(module_scope)
