# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cluster_pb2 as cluster__pb2
import base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='ProtoMsg',
  syntax='proto3',
  serialized_pb=_b('\n\x0blogin.proto\x12\x08ProtoMsg\x1a\rcluster.proto\x1a\nbase.proto\"E\n\x18PbSvrRegisterLoginReqMsg\x12)\n\x08svr_info\x18\x01 \x01(\x0b\x32\x17.ProtoMsg.PbSvrBaseInfo\"6\n\x18PbSvrRegisterLoginResMsg\x12\x1a\n\x03ret\x18\x01 \x01(\x0b\x32\r.ProtoMsg.Ret\"\xd1\x01\n\x15PbCsPlayerLoginReqMsg\x12)\n\nlogin_type\x18\x01 \x01(\x0e\x32\x15.ProtoMsg.emLoginType\x12+\n\x0b\x64\x65vice_type\x18\x02 \x01(\x0e\x32\x16.ProtoMsg.emDeviceType\x12\x13\n\x0b\x64\x65vice_desc\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x15\n\rplatfom_token\x18\x05 \x01(\t\x12\x11\n\tuser_name\x18\x06 \x01(\t\x12\x10\n\x08user_pwd\x18\x07 \x01(\t\"@\n\x15PbCsPlayerLoginResMsg\x12\x1a\n\x03ret\x18\x01 \x01(\x0b\x32\r.ProtoMsg.Ret\x12\x0b\n\x03uid\x18\x02 \x01(\x04\"\x16\n\x14PbCsPlayerBindReqMsg\"2\n\x14PbCsPlayerBindResMsg\x12\x1a\n\x03ret\x18\x01 \x01(\x0b\x32\r.ProtoMsg.Ret*\x93\x01\n\x0b\x65mLoginType\x12\x16\n\x12Login_type_invalid\x10\x00\x12\x16\n\x12Login_type_visitor\x10\x01\x12\x13\n\x0fLogin_type_user\x10\x02\x12\x11\n\rLogin_type_qq\x10\x03\x12\x15\n\x11Login_type_wechat\x10\x04\x12\x15\n\x11Login_type_alipay\x10\x05*\x99\x01\n\x0c\x65mDeviceType\x12\x17\n\x13\x44\x65vice_type_invalid\x10\x00\x12\x17\n\x13\x44\x65vice_type_android\x10\x01\x12\x13\n\x0f\x44\x65vice_type_ios\x10\x02\x12\x14\n\x10\x44\x65vice_type_ipad\x10\x03\x12\x13\n\x0f\x44\x65vice_type_mac\x10\x04\x12\x17\n\x13\x44\x65vice_type_windows\x10\x05\x62\x06proto3')
  ,
  dependencies=[cluster__pb2.DESCRIPTOR,base__pb2.DESCRIPTOR,])

_EMLOGINTYPE = _descriptor.EnumDescriptor(
  name='emLoginType',
  full_name='ProtoMsg.emLoginType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Login_type_invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Login_type_visitor', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Login_type_user', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Login_type_qq', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Login_type_wechat', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Login_type_alipay', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=534,
  serialized_end=681,
)
_sym_db.RegisterEnumDescriptor(_EMLOGINTYPE)

emLoginType = enum_type_wrapper.EnumTypeWrapper(_EMLOGINTYPE)
_EMDEVICETYPE = _descriptor.EnumDescriptor(
  name='emDeviceType',
  full_name='ProtoMsg.emDeviceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Device_type_invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Device_type_android', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Device_type_ios', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Device_type_ipad', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Device_type_mac', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Device_type_windows', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=684,
  serialized_end=837,
)
_sym_db.RegisterEnumDescriptor(_EMDEVICETYPE)

emDeviceType = enum_type_wrapper.EnumTypeWrapper(_EMDEVICETYPE)
Login_type_invalid = 0
Login_type_visitor = 1
Login_type_user = 2
Login_type_qq = 3
Login_type_wechat = 4
Login_type_alipay = 5
Device_type_invalid = 0
Device_type_android = 1
Device_type_ios = 2
Device_type_ipad = 3
Device_type_mac = 4
Device_type_windows = 5



_PBSVRREGISTERLOGINREQMSG = _descriptor.Descriptor(
  name='PbSvrRegisterLoginReqMsg',
  full_name='ProtoMsg.PbSvrRegisterLoginReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svr_info', full_name='ProtoMsg.PbSvrRegisterLoginReqMsg.svr_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=121,
)


_PBSVRREGISTERLOGINRESMSG = _descriptor.Descriptor(
  name='PbSvrRegisterLoginResMsg',
  full_name='ProtoMsg.PbSvrRegisterLoginResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoMsg.PbSvrRegisterLoginResMsg.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=177,
)


_PBCSPLAYERLOGINREQMSG = _descriptor.Descriptor(
  name='PbCsPlayerLoginReqMsg',
  full_name='ProtoMsg.PbCsPlayerLoginReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login_type', full_name='ProtoMsg.PbCsPlayerLoginReqMsg.login_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='ProtoMsg.PbCsPlayerLoginReqMsg.device_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_desc', full_name='ProtoMsg.PbCsPlayerLoginReqMsg.device_desc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='ProtoMsg.PbCsPlayerLoginReqMsg.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platfom_token', full_name='ProtoMsg.PbCsPlayerLoginReqMsg.platfom_token', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='ProtoMsg.PbCsPlayerLoginReqMsg.user_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_pwd', full_name='ProtoMsg.PbCsPlayerLoginReqMsg.user_pwd', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=389,
)


_PBCSPLAYERLOGINRESMSG = _descriptor.Descriptor(
  name='PbCsPlayerLoginResMsg',
  full_name='ProtoMsg.PbCsPlayerLoginResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoMsg.PbCsPlayerLoginResMsg.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='ProtoMsg.PbCsPlayerLoginResMsg.uid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=455,
)


_PBCSPLAYERBINDREQMSG = _descriptor.Descriptor(
  name='PbCsPlayerBindReqMsg',
  full_name='ProtoMsg.PbCsPlayerBindReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=479,
)


_PBCSPLAYERBINDRESMSG = _descriptor.Descriptor(
  name='PbCsPlayerBindResMsg',
  full_name='ProtoMsg.PbCsPlayerBindResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoMsg.PbCsPlayerBindResMsg.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=531,
)

_PBSVRREGISTERLOGINREQMSG.fields_by_name['svr_info'].message_type = cluster__pb2._PBSVRBASEINFO
_PBSVRREGISTERLOGINRESMSG.fields_by_name['ret'].message_type = base__pb2._RET
_PBCSPLAYERLOGINREQMSG.fields_by_name['login_type'].enum_type = _EMLOGINTYPE
_PBCSPLAYERLOGINREQMSG.fields_by_name['device_type'].enum_type = _EMDEVICETYPE
_PBCSPLAYERLOGINRESMSG.fields_by_name['ret'].message_type = base__pb2._RET
_PBCSPLAYERBINDRESMSG.fields_by_name['ret'].message_type = base__pb2._RET
DESCRIPTOR.message_types_by_name['PbSvrRegisterLoginReqMsg'] = _PBSVRREGISTERLOGINREQMSG
DESCRIPTOR.message_types_by_name['PbSvrRegisterLoginResMsg'] = _PBSVRREGISTERLOGINRESMSG
DESCRIPTOR.message_types_by_name['PbCsPlayerLoginReqMsg'] = _PBCSPLAYERLOGINREQMSG
DESCRIPTOR.message_types_by_name['PbCsPlayerLoginResMsg'] = _PBCSPLAYERLOGINRESMSG
DESCRIPTOR.message_types_by_name['PbCsPlayerBindReqMsg'] = _PBCSPLAYERBINDREQMSG
DESCRIPTOR.message_types_by_name['PbCsPlayerBindResMsg'] = _PBCSPLAYERBINDRESMSG
DESCRIPTOR.enum_types_by_name['emLoginType'] = _EMLOGINTYPE
DESCRIPTOR.enum_types_by_name['emDeviceType'] = _EMDEVICETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbSvrRegisterLoginReqMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterLoginReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERLOGINREQMSG,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterLoginReqMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterLoginReqMsg)

PbSvrRegisterLoginResMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterLoginResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERLOGINRESMSG,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterLoginResMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterLoginResMsg)

PbCsPlayerLoginReqMsg = _reflection.GeneratedProtocolMessageType('PbCsPlayerLoginReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBCSPLAYERLOGINREQMSG,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbCsPlayerLoginReqMsg)
  ))
_sym_db.RegisterMessage(PbCsPlayerLoginReqMsg)

PbCsPlayerLoginResMsg = _reflection.GeneratedProtocolMessageType('PbCsPlayerLoginResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBCSPLAYERLOGINRESMSG,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbCsPlayerLoginResMsg)
  ))
_sym_db.RegisterMessage(PbCsPlayerLoginResMsg)

PbCsPlayerBindReqMsg = _reflection.GeneratedProtocolMessageType('PbCsPlayerBindReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBCSPLAYERBINDREQMSG,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbCsPlayerBindReqMsg)
  ))
_sym_db.RegisterMessage(PbCsPlayerBindReqMsg)

PbCsPlayerBindResMsg = _reflection.GeneratedProtocolMessageType('PbCsPlayerBindResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBCSPLAYERBINDRESMSG,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbCsPlayerBindResMsg)
  ))
_sym_db.RegisterMessage(PbCsPlayerBindResMsg)


# @@protoc_insertion_point(module_scope)
