# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mid_abnormal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ret_base_pb2 as ret__base__pb2
import public_message_pb2 as public__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mid_abnormal.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x12mid_abnormal.proto\x12\nQuoteProto\x1a\x0eret_base.proto\x1a\x14public_message.proto\"g\n\x12MidAbnormalRequest\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\x12\n\nstock_code\x18\x02 \x02(\t\x12\r\n\x05index\x18\x03 \x02(\x05\x12\r\n\x05\x63ount\x18\x04 \x02(\r\x12\x11\n\tdirection\x18\x05 \x01(\r\"v\n\x13MidAbnormalResponse\x12\x1c\n\x03ret\x18\x01 \x02(\x0b\x32\x0f.QuoteProto.Ret\x12,\n\x08\x61\x62_infos\x18\x02 \x03(\x0b\x32\x1a.QuoteProto.MidAbnormalMsg\x12\x13\n\x0btotal_count\x18\x03 \x02(\r')
  ,
  dependencies=[ret__base__pb2.DESCRIPTOR,public__message__pb2.DESCRIPTOR,])




_MIDABNORMALREQUEST = _descriptor.Descriptor(
  name='MidAbnormalRequest',
  full_name='QuoteProto.MidAbnormalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='QuoteProto.MidAbnormalRequest.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stock_code', full_name='QuoteProto.MidAbnormalRequest.stock_code', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='QuoteProto.MidAbnormalRequest.index', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='QuoteProto.MidAbnormalRequest.count', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='QuoteProto.MidAbnormalRequest.direction', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=175,
)


_MIDABNORMALRESPONSE = _descriptor.Descriptor(
  name='MidAbnormalResponse',
  full_name='QuoteProto.MidAbnormalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.MidAbnormalResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ab_infos', full_name='QuoteProto.MidAbnormalResponse.ab_infos', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_count', full_name='QuoteProto.MidAbnormalResponse.total_count', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=295,
)

_MIDABNORMALRESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_MIDABNORMALRESPONSE.fields_by_name['ab_infos'].message_type = public__message__pb2._MIDABNORMALMSG
DESCRIPTOR.message_types_by_name['MidAbnormalRequest'] = _MIDABNORMALREQUEST
DESCRIPTOR.message_types_by_name['MidAbnormalResponse'] = _MIDABNORMALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MidAbnormalRequest = _reflection.GeneratedProtocolMessageType('MidAbnormalRequest', (_message.Message,), dict(
  DESCRIPTOR = _MIDABNORMALREQUEST,
  __module__ = 'mid_abnormal_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.MidAbnormalRequest)
  ))
_sym_db.RegisterMessage(MidAbnormalRequest)

MidAbnormalResponse = _reflection.GeneratedProtocolMessageType('MidAbnormalResponse', (_message.Message,), dict(
  DESCRIPTOR = _MIDABNORMALRESPONSE,
  __module__ = 'mid_abnormal_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.MidAbnormalResponse)
  ))
_sym_db.RegisterMessage(MidAbnormalResponse)


# @@protoc_insertion_point(module_scope)
