# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mongo_agency.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import public_message_pb2 as public__message__pb2
import ret_base_pb2 as ret__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mongo_agency.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x12mongo_agency.proto\x12\nQuoteProto\x1a\x14public_message.proto\x1a\x0eret_base.proto\"\x97\x01\n\x0cQueryRequest\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.QuoteProto.QueryType\x12\x11\n\toperation\x18\x02 \x02(\t\x12\x0e\n\x06\x64\x62name\x18\x03 \x02(\t\x12\x12\n\ncollection\x18\x04 \x02(\t\x12\x0e\n\x06\x61mount\x18\x05 \x02(\x05\x12\x0c\n\x04sort\x18\x06 \x02(\t\x12\r\n\x05\x61sync\x18\x07 \x01(\x08\"s\n\x12QueryKlineResponse\x12\x1c\n\x03ret\x18\x01 \x02(\x0b\x32\x0f.QuoteProto.Ret\x12&\n\x07op_type\x18\x02 \x01(\x0e\x32\x15.QuoteProto.QueryType\x12\x17\n\x0fmongo_bson_data\x18\x03 \x01(\x0c*_\n\tQueryType\x12\x0e\n\nQueryKline\x10\x00\x12\x0f\n\x0bInsertKline\x10\x01\x12\x0f\n\x0bUpdateKline\x10\x02\x12\x0f\n\x0b\x44\x65leteKline\x10\x03\x12\x0f\n\x0bUpsertKline\x10\x04')
  ,
  dependencies=[public__message__pb2.DESCRIPTOR,ret__base__pb2.DESCRIPTOR,])

_QUERYTYPE = _descriptor.EnumDescriptor(
  name='QueryType',
  full_name='QuoteProto.QueryType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QueryKline', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InsertKline', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UpdateKline', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DeleteKline', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UpsertKline', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=343,
  serialized_end=438,
)
_sym_db.RegisterEnumDescriptor(_QUERYTYPE)

QueryType = enum_type_wrapper.EnumTypeWrapper(_QUERYTYPE)
QueryKline = 0
InsertKline = 1
UpdateKline = 2
DeleteKline = 3
UpsertKline = 4



_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='QuoteProto.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='QuoteProto.QueryRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operation', full_name='QuoteProto.QueryRequest.operation', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dbname', full_name='QuoteProto.QueryRequest.dbname', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collection', full_name='QuoteProto.QueryRequest.collection', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='QuoteProto.QueryRequest.amount', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort', full_name='QuoteProto.QueryRequest.sort', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='async', full_name='QuoteProto.QueryRequest.async', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=224,
)


_QUERYKLINERESPONSE = _descriptor.Descriptor(
  name='QueryKlineResponse',
  full_name='QuoteProto.QueryKlineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.QueryKlineResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_type', full_name='QuoteProto.QueryKlineResponse.op_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mongo_bson_data', full_name='QuoteProto.QueryKlineResponse.mongo_bson_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=341,
)

_QUERYREQUEST.fields_by_name['type'].enum_type = _QUERYTYPE
_QUERYKLINERESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_QUERYKLINERESPONSE.fields_by_name['op_type'].enum_type = _QUERYTYPE
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryKlineResponse'] = _QUERYKLINERESPONSE
DESCRIPTOR.enum_types_by_name['QueryType'] = _QUERYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUEST,
  __module__ = 'mongo_agency_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.QueryRequest)
  ))
_sym_db.RegisterMessage(QueryRequest)

QueryKlineResponse = _reflection.GeneratedProtocolMessageType('QueryKlineResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYKLINERESPONSE,
  __module__ = 'mongo_agency_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.QueryKlineResponse)
  ))
_sym_db.RegisterMessage(QueryKlineResponse)


# @@protoc_insertion_point(module_scope)
