# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rise_fall_monitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ret_base_pb2 as ret__base__pb2
import public_message_pb2 as public__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rise_fall_monitor.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x17rise_fall_monitor.proto\x12\nQuoteProto\x1a\x0eret_base.proto\x1a\x14public_message.proto\"!\n\x1fRFMonitorNumInfoOptionalRequest\"p\n RFMonitorNumInfoOptionalResponse\x12\x1c\n\x03ret\x18\x01 \x01(\x0b\x32\x0f.QuoteProto.Ret\x12.\n\x03msg\x18\x02 \x01(\x0b\x32!.QuoteProto.RiseFallMonitorNumMsg\"\xd0\x01\n\x15\x42\x61tchRFMonitorRequest\x12)\n\x06m_type\x18\x01 \x02(\x0e\x32\x19.QuoteProto.RFMonitorType\x12\x30\n\tsort_type\x18\x02 \x02(\x0e\x32\x1d.QuoteProto.RiseFallMSortType\x12\x0f\n\x07is_desc\x18\x03 \x02(\x08\x12\r\n\x05index\x18\x04 \x02(\x05\x12\x13\n\x0b\x63ount_range\x18\x05 \x02(\x05\x12%\n\x08msg_mask\x18\x06 \x01(\x0b\x32\x13.QuoteProto.MsgMask\"k\n\x16\x42\x61tchRFMonitorResponse\x12\x1c\n\x03ret\x18\x01 \x01(\x0b\x32\x0f.QuoteProto.Ret\x12\x11\n\ttotal_cnt\x18\x02 \x01(\x05\x12 \n\x03stk\x18\x03 \x03(\x0b\x32\x13.QuoteProto.RateMsg\"s\n\x14RFMGropeTypesReqItem\x12)\n\x06m_type\x18\x01 \x02(\x0e\x32\x19.QuoteProto.RFMonitorType\x12\x30\n\tsort_type\x18\x02 \x02(\x0e\x32\x1d.QuoteProto.RiseFallMSortType\"L\n\x14RFMGroupTypesRequest\x12\x34\n\nitem_types\x18\x01 \x03(\x0b\x32 .QuoteProto.RFMGropeTypesReqItem\"m\n\x14RFMGropeTypesResItem\x12\x33\n\titem_type\x18\x01 \x02(\x0b\x32 .QuoteProto.RFMGropeTypesReqItem\x12 \n\x03msg\x18\x02 \x02(\x0b\x32\x13.QuoteProto.RateMsg\"f\n\x15RFMGroupTypesResponse\x12\x1c\n\x03ret\x18\x01 \x01(\x0b\x32\x0f.QuoteProto.Ret\x12/\n\x05items\x18\x02 \x03(\x0b\x32 .QuoteProto.RFMGropeTypesResItem*\x95\x02\n\x11RiseFallMSortType\x12\x14\n\x10rfm_sort_invalid\x10\x00\x12\x14\n\x10rfm_sort_fb_rise\x10\x01\x12\x14\n\x10rfm_sort_fb_time\x10\x02\x12\x16\n\x12rfm_sort_zt_volume\x10\x03\x12\x16\n\x12rfm_sort_dt_volumn\x10\x04\x12\x14\n\x10rfm_sort_dt_time\x10\x05\x12\x14\n\x10rfm_sort_zb_time\x10\x06\x12\x13\n\x0frfm_sort_zb_num\x10\x07\x12\x17\n\x13rfm_sort_main_funds\x10\x08\x12\x19\n\x15rfm_sort_zt_open_time\x10\t\x12\x19\n\x15rfm_sort_dt_open_time\x10\n')
  ,
  dependencies=[ret__base__pb2.DESCRIPTOR,public__message__pb2.DESCRIPTOR,])

_RISEFALLMSORTTYPE = _descriptor.EnumDescriptor(
  name='RiseFallMSortType',
  full_name='QuoteProto.RiseFallMSortType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_fb_rise', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_fb_time', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_zt_volume', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_dt_volumn', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_dt_time', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_zb_time', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_zb_num', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_main_funds', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_zt_open_time', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='rfm_sort_dt_open_time', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=957,
  serialized_end=1234,
)
_sym_db.RegisterEnumDescriptor(_RISEFALLMSORTTYPE)

RiseFallMSortType = enum_type_wrapper.EnumTypeWrapper(_RISEFALLMSORTTYPE)
rfm_sort_invalid = 0
rfm_sort_fb_rise = 1
rfm_sort_fb_time = 2
rfm_sort_zt_volume = 3
rfm_sort_dt_volumn = 4
rfm_sort_dt_time = 5
rfm_sort_zb_time = 6
rfm_sort_zb_num = 7
rfm_sort_main_funds = 8
rfm_sort_zt_open_time = 9
rfm_sort_dt_open_time = 10



_RFMONITORNUMINFOOPTIONALREQUEST = _descriptor.Descriptor(
  name='RFMonitorNumInfoOptionalRequest',
  full_name='QuoteProto.RFMonitorNumInfoOptionalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=110,
)


_RFMONITORNUMINFOOPTIONALRESPONSE = _descriptor.Descriptor(
  name='RFMonitorNumInfoOptionalResponse',
  full_name='QuoteProto.RFMonitorNumInfoOptionalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.RFMonitorNumInfoOptionalResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='QuoteProto.RFMonitorNumInfoOptionalResponse.msg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=224,
)


_BATCHRFMONITORREQUEST = _descriptor.Descriptor(
  name='BatchRFMonitorRequest',
  full_name='QuoteProto.BatchRFMonitorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_type', full_name='QuoteProto.BatchRFMonitorRequest.m_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort_type', full_name='QuoteProto.BatchRFMonitorRequest.sort_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_desc', full_name='QuoteProto.BatchRFMonitorRequest.is_desc', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='QuoteProto.BatchRFMonitorRequest.index', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count_range', full_name='QuoteProto.BatchRFMonitorRequest.count_range', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_mask', full_name='QuoteProto.BatchRFMonitorRequest.msg_mask', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=435,
)


_BATCHRFMONITORRESPONSE = _descriptor.Descriptor(
  name='BatchRFMonitorResponse',
  full_name='QuoteProto.BatchRFMonitorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.BatchRFMonitorResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_cnt', full_name='QuoteProto.BatchRFMonitorResponse.total_cnt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stk', full_name='QuoteProto.BatchRFMonitorResponse.stk', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=544,
)


_RFMGROPETYPESREQITEM = _descriptor.Descriptor(
  name='RFMGropeTypesReqItem',
  full_name='QuoteProto.RFMGropeTypesReqItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_type', full_name='QuoteProto.RFMGropeTypesReqItem.m_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort_type', full_name='QuoteProto.RFMGropeTypesReqItem.sort_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=661,
)


_RFMGROUPTYPESREQUEST = _descriptor.Descriptor(
  name='RFMGroupTypesRequest',
  full_name='QuoteProto.RFMGroupTypesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_types', full_name='QuoteProto.RFMGroupTypesRequest.item_types', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=739,
)


_RFMGROPETYPESRESITEM = _descriptor.Descriptor(
  name='RFMGropeTypesResItem',
  full_name='QuoteProto.RFMGropeTypesResItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_type', full_name='QuoteProto.RFMGropeTypesResItem.item_type', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='QuoteProto.RFMGropeTypesResItem.msg', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=741,
  serialized_end=850,
)


_RFMGROUPTYPESRESPONSE = _descriptor.Descriptor(
  name='RFMGroupTypesResponse',
  full_name='QuoteProto.RFMGroupTypesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.RFMGroupTypesResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='QuoteProto.RFMGroupTypesResponse.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=852,
  serialized_end=954,
)

_RFMONITORNUMINFOOPTIONALRESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_RFMONITORNUMINFOOPTIONALRESPONSE.fields_by_name['msg'].message_type = public__message__pb2._RISEFALLMONITORNUMMSG
_BATCHRFMONITORREQUEST.fields_by_name['m_type'].enum_type = public__message__pb2._RFMONITORTYPE
_BATCHRFMONITORREQUEST.fields_by_name['sort_type'].enum_type = _RISEFALLMSORTTYPE
_BATCHRFMONITORREQUEST.fields_by_name['msg_mask'].message_type = public__message__pb2._MSGMASK
_BATCHRFMONITORRESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_BATCHRFMONITORRESPONSE.fields_by_name['stk'].message_type = public__message__pb2._RATEMSG
_RFMGROPETYPESREQITEM.fields_by_name['m_type'].enum_type = public__message__pb2._RFMONITORTYPE
_RFMGROPETYPESREQITEM.fields_by_name['sort_type'].enum_type = _RISEFALLMSORTTYPE
_RFMGROUPTYPESREQUEST.fields_by_name['item_types'].message_type = _RFMGROPETYPESREQITEM
_RFMGROPETYPESRESITEM.fields_by_name['item_type'].message_type = _RFMGROPETYPESREQITEM
_RFMGROPETYPESRESITEM.fields_by_name['msg'].message_type = public__message__pb2._RATEMSG
_RFMGROUPTYPESRESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_RFMGROUPTYPESRESPONSE.fields_by_name['items'].message_type = _RFMGROPETYPESRESITEM
DESCRIPTOR.message_types_by_name['RFMonitorNumInfoOptionalRequest'] = _RFMONITORNUMINFOOPTIONALREQUEST
DESCRIPTOR.message_types_by_name['RFMonitorNumInfoOptionalResponse'] = _RFMONITORNUMINFOOPTIONALRESPONSE
DESCRIPTOR.message_types_by_name['BatchRFMonitorRequest'] = _BATCHRFMONITORREQUEST
DESCRIPTOR.message_types_by_name['BatchRFMonitorResponse'] = _BATCHRFMONITORRESPONSE
DESCRIPTOR.message_types_by_name['RFMGropeTypesReqItem'] = _RFMGROPETYPESREQITEM
DESCRIPTOR.message_types_by_name['RFMGroupTypesRequest'] = _RFMGROUPTYPESREQUEST
DESCRIPTOR.message_types_by_name['RFMGropeTypesResItem'] = _RFMGROPETYPESRESITEM
DESCRIPTOR.message_types_by_name['RFMGroupTypesResponse'] = _RFMGROUPTYPESRESPONSE
DESCRIPTOR.enum_types_by_name['RiseFallMSortType'] = _RISEFALLMSORTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RFMonitorNumInfoOptionalRequest = _reflection.GeneratedProtocolMessageType('RFMonitorNumInfoOptionalRequest', (_message.Message,), dict(
  DESCRIPTOR = _RFMONITORNUMINFOOPTIONALREQUEST,
  __module__ = 'rise_fall_monitor_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.RFMonitorNumInfoOptionalRequest)
  ))
_sym_db.RegisterMessage(RFMonitorNumInfoOptionalRequest)

RFMonitorNumInfoOptionalResponse = _reflection.GeneratedProtocolMessageType('RFMonitorNumInfoOptionalResponse', (_message.Message,), dict(
  DESCRIPTOR = _RFMONITORNUMINFOOPTIONALRESPONSE,
  __module__ = 'rise_fall_monitor_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.RFMonitorNumInfoOptionalResponse)
  ))
_sym_db.RegisterMessage(RFMonitorNumInfoOptionalResponse)

BatchRFMonitorRequest = _reflection.GeneratedProtocolMessageType('BatchRFMonitorRequest', (_message.Message,), dict(
  DESCRIPTOR = _BATCHRFMONITORREQUEST,
  __module__ = 'rise_fall_monitor_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.BatchRFMonitorRequest)
  ))
_sym_db.RegisterMessage(BatchRFMonitorRequest)

BatchRFMonitorResponse = _reflection.GeneratedProtocolMessageType('BatchRFMonitorResponse', (_message.Message,), dict(
  DESCRIPTOR = _BATCHRFMONITORRESPONSE,
  __module__ = 'rise_fall_monitor_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.BatchRFMonitorResponse)
  ))
_sym_db.RegisterMessage(BatchRFMonitorResponse)

RFMGropeTypesReqItem = _reflection.GeneratedProtocolMessageType('RFMGropeTypesReqItem', (_message.Message,), dict(
  DESCRIPTOR = _RFMGROPETYPESREQITEM,
  __module__ = 'rise_fall_monitor_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.RFMGropeTypesReqItem)
  ))
_sym_db.RegisterMessage(RFMGropeTypesReqItem)

RFMGroupTypesRequest = _reflection.GeneratedProtocolMessageType('RFMGroupTypesRequest', (_message.Message,), dict(
  DESCRIPTOR = _RFMGROUPTYPESREQUEST,
  __module__ = 'rise_fall_monitor_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.RFMGroupTypesRequest)
  ))
_sym_db.RegisterMessage(RFMGroupTypesRequest)

RFMGropeTypesResItem = _reflection.GeneratedProtocolMessageType('RFMGropeTypesResItem', (_message.Message,), dict(
  DESCRIPTOR = _RFMGROPETYPESRESITEM,
  __module__ = 'rise_fall_monitor_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.RFMGropeTypesResItem)
  ))
_sym_db.RegisterMessage(RFMGropeTypesResItem)

RFMGroupTypesResponse = _reflection.GeneratedProtocolMessageType('RFMGroupTypesResponse', (_message.Message,), dict(
  DESCRIPTOR = _RFMGROUPTYPESRESPONSE,
  __module__ = 'rise_fall_monitor_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.RFMGroupTypesResponse)
  ))
_sym_db.RegisterMessage(RFMGroupTypesResponse)


# @@protoc_insertion_point(module_scope)
