# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ret_base_pb2 as ret__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='search.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x0csearch.proto\x12\nQuoteProto\x1a\x0eret_base.proto\"5\n\tCodeTable\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"M\n\x10QueryCodeRequest\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x16.QuoteProto.SearchType\x12\x13\n\x0bsearch_word\x18\x02 \x02(\t\"]\n\x11QueryCodeResponse\x12\x1c\n\x03ret\x18\x01 \x02(\x0b\x32\x0f.QuoteProto.Ret\x12*\n\x0b\x63odes_table\x18\x03 \x03(\x0b\x32\x15.QuoteProto.CodeTable*N\n\nSearchType\x12\x0e\n\nFuzzyQuery\x10\x00\x12\r\n\tCodeQuery\x10\x01\x12\x0f\n\x0bSampleQuery\x10\x02\x12\x10\n\x0c\x43hineseQuery\x10\x04')
  ,
  dependencies=[ret__base__pb2.DESCRIPTOR,])

_SEARCHTYPE = _descriptor.EnumDescriptor(
  name='SearchType',
  full_name='QuoteProto.SearchType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FuzzyQuery', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CodeQuery', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SampleQuery', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ChineseQuery', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=273,
  serialized_end=351,
)
_sym_db.RegisterEnumDescriptor(_SEARCHTYPE)

SearchType = enum_type_wrapper.EnumTypeWrapper(_SEARCHTYPE)
FuzzyQuery = 0
CodeQuery = 1
SampleQuery = 2
ChineseQuery = 4



_CODETABLE = _descriptor.Descriptor(
  name='CodeTable',
  full_name='QuoteProto.CodeTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='QuoteProto.CodeTable.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='QuoteProto.CodeTable.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='QuoteProto.CodeTable.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=97,
)


_QUERYCODEREQUEST = _descriptor.Descriptor(
  name='QueryCodeRequest',
  full_name='QuoteProto.QueryCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='QuoteProto.QueryCodeRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='search_word', full_name='QuoteProto.QueryCodeRequest.search_word', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=176,
)


_QUERYCODERESPONSE = _descriptor.Descriptor(
  name='QueryCodeResponse',
  full_name='QuoteProto.QueryCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.QueryCodeResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codes_table', full_name='QuoteProto.QueryCodeResponse.codes_table', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=271,
)

_QUERYCODEREQUEST.fields_by_name['type'].enum_type = _SEARCHTYPE
_QUERYCODERESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_QUERYCODERESPONSE.fields_by_name['codes_table'].message_type = _CODETABLE
DESCRIPTOR.message_types_by_name['CodeTable'] = _CODETABLE
DESCRIPTOR.message_types_by_name['QueryCodeRequest'] = _QUERYCODEREQUEST
DESCRIPTOR.message_types_by_name['QueryCodeResponse'] = _QUERYCODERESPONSE
DESCRIPTOR.enum_types_by_name['SearchType'] = _SEARCHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CodeTable = _reflection.GeneratedProtocolMessageType('CodeTable', (_message.Message,), dict(
  DESCRIPTOR = _CODETABLE,
  __module__ = 'search_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.CodeTable)
  ))
_sym_db.RegisterMessage(CodeTable)

QueryCodeRequest = _reflection.GeneratedProtocolMessageType('QueryCodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYCODEREQUEST,
  __module__ = 'search_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.QueryCodeRequest)
  ))
_sym_db.RegisterMessage(QueryCodeRequest)

QueryCodeResponse = _reflection.GeneratedProtocolMessageType('QueryCodeResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYCODERESPONSE,
  __module__ = 'search_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.QueryCodeResponse)
  ))
_sym_db.RegisterMessage(QueryCodeResponse)


# @@protoc_insertion_point(module_scope)
