# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: short_motion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ret_base_pb2 as ret__base__pb2
import public_message_pb2 as public__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='short_motion.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x12short_motion.proto\x12\nQuoteProto\x1a\x0eret_base.proto\x1a\x14public_message.proto\"\x85\x01\n\x17\x42\x61tchShortMotionRequest\x12\x35\n\nshort_type\x18\x01 \x02(\x0e\x32!.QuoteProto.ShortMotionClientType\x12\x0f\n\x07is_desc\x18\x02 \x02(\x08\x12\r\n\x05index\x18\x03 \x02(\x05\x12\x13\n\x0b\x63ount_range\x18\x04 \x02(\x05\"t\n\x18\x42\x61tchShortMotionResponse\x12\x1c\n\x03ret\x18\x01 \x02(\x0b\x32\x0f.QuoteProto.Ret\x12\'\n\x03stk\x18\x02 \x03(\x0b\x32\x1a.QuoteProto.ShortMotionMsg\x12\x11\n\ttotal_cnt\x18\x03 \x01(\x05')
  ,
  dependencies=[ret__base__pb2.DESCRIPTOR,public__message__pb2.DESCRIPTOR,])




_BATCHSHORTMOTIONREQUEST = _descriptor.Descriptor(
  name='BatchShortMotionRequest',
  full_name='QuoteProto.BatchShortMotionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='short_type', full_name='QuoteProto.BatchShortMotionRequest.short_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_desc', full_name='QuoteProto.BatchShortMotionRequest.is_desc', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='QuoteProto.BatchShortMotionRequest.index', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count_range', full_name='QuoteProto.BatchShortMotionRequest.count_range', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=206,
)


_BATCHSHORTMOTIONRESPONSE = _descriptor.Descriptor(
  name='BatchShortMotionResponse',
  full_name='QuoteProto.BatchShortMotionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.BatchShortMotionResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stk', full_name='QuoteProto.BatchShortMotionResponse.stk', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_cnt', full_name='QuoteProto.BatchShortMotionResponse.total_cnt', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=324,
)

_BATCHSHORTMOTIONREQUEST.fields_by_name['short_type'].enum_type = public__message__pb2._SHORTMOTIONCLIENTTYPE
_BATCHSHORTMOTIONRESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_BATCHSHORTMOTIONRESPONSE.fields_by_name['stk'].message_type = public__message__pb2._SHORTMOTIONMSG
DESCRIPTOR.message_types_by_name['BatchShortMotionRequest'] = _BATCHSHORTMOTIONREQUEST
DESCRIPTOR.message_types_by_name['BatchShortMotionResponse'] = _BATCHSHORTMOTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BatchShortMotionRequest = _reflection.GeneratedProtocolMessageType('BatchShortMotionRequest', (_message.Message,), dict(
  DESCRIPTOR = _BATCHSHORTMOTIONREQUEST,
  __module__ = 'short_motion_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.BatchShortMotionRequest)
  ))
_sym_db.RegisterMessage(BatchShortMotionRequest)

BatchShortMotionResponse = _reflection.GeneratedProtocolMessageType('BatchShortMotionResponse', (_message.Message,), dict(
  DESCRIPTOR = _BATCHSHORTMOTIONRESPONSE,
  __module__ = 'short_motion_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.BatchShortMotionResponse)
  ))
_sym_db.RegisterMessage(BatchShortMotionResponse)


# @@protoc_insertion_point(module_scope)
