# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ss_protoid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ss_protoid.proto',
  package='ProtoMsg',
  syntax='proto3',
  serialized_pb=_b('\n\x10ss_protoid.proto\x12\x08ProtoMsg*\xa2\x05\n\temSSMsgId\x12\x13\n\x0fSVR_MSG_INVALID\x10\x00\x12\x16\n\x12SVR_MSG_HEART_BEAT\x10\x01\x12\x13\n\rSVR_MSG_BEGIN\x10\xc0\x9a\x0c\x12&\n SVR_MSG_COMMON_PUSH_PLAYER_SVRID\x10\xc1\x9a\x0c\x12\x18\n\x12SVR_MSG_COMMON_END\x10\xa7\xa2\x0c\x12\x1b\n\x15SVR_MSG_CLUSTER_BEGIN\x10\xa8\xa2\x0c\x12\x1e\n\x18SVR_MSG_REGISTER_CLUSTER\x10\xa9\xa2\x0c\x12\x1b\n\x15SVR_MSG_BROAD_CLUSTER\x10\xaa\xa2\x0c\x12\x19\n\x13SVR_MSG_CLUSTER_END\x10\x8f\xaa\x0c\x12\x18\n\x12SVR_MSG_GAME_BEGIN\x10\xd0\xe8\x0c\x12\x1b\n\x15SVR_MSG_REGISTER_GAME\x10\xd1\xe8\x0c\x12\x18\n\x12SVR_MSG_GAME_LOGIN\x10\xd2\xe8\x0c\x12\x16\n\x10SVR_MSG_GAME_END\x10\xdf\xb6\r\x12\x19\n\x13SVR_MSG_WORLD_BEGIN\x10\xe0\xb6\r\x12\x1c\n\x16SVR_MSG_REGISTER_WORLD\x10\xe1\xb6\r\x12\x19\n\x13SVR_MSG_WORLD_LOGIN\x10\xe2\xb6\r\x12\x17\n\x11SVR_MSG_WORLD_END\x10\xef\x84\x0e\x12\x19\n\x13SVR_MSG_LOGIN_BEGIN\x10\xf0\x84\x0e\x12\x1c\n\x16SVR_MSG_REGISTER_LOGIN\x10\xf1\x84\x0e\x12\x17\n\x11SVR_MSG_LOGIN_END\x10\xff\xd2\x0e\x12\x16\n\x10SVR_MSG_DB_BEGIN\x10\x80\xd3\x0e\x12\x19\n\x13SVR_MSG_REGISTER_DB\x10\x81\xd3\x0e\x12\x18\n\x12SVR_MSG_DB_SERVICE\x10\x82\xd3\x0e\x12\x14\n\x0eSVR_MSG_DB_END\x10\x8f\xa1\x0f\x12\x11\n\x0bSVR_MSG_END\x10\xdf\xa7\x12\x62\x06proto3')
)

_EMSSMSGID = _descriptor.EnumDescriptor(
  name='emSSMsgId',
  full_name='ProtoMsg.emSSMsgId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_HEART_BEAT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_BEGIN', index=2, number=200000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_COMMON_PUSH_PLAYER_SVRID', index=3, number=200001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_COMMON_END', index=4, number=200999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_CLUSTER_BEGIN', index=5, number=201000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_REGISTER_CLUSTER', index=6, number=201001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_BROAD_CLUSTER', index=7, number=201002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_CLUSTER_END', index=8, number=201999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_GAME_BEGIN', index=9, number=210000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_REGISTER_GAME', index=10, number=210001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_GAME_LOGIN', index=11, number=210002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_GAME_END', index=12, number=219999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_WORLD_BEGIN', index=13, number=220000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_REGISTER_WORLD', index=14, number=220001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_WORLD_LOGIN', index=15, number=220002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_WORLD_END', index=16, number=229999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_LOGIN_BEGIN', index=17, number=230000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_REGISTER_LOGIN', index=18, number=230001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_LOGIN_END', index=19, number=239999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_DB_BEGIN', index=20, number=240000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_REGISTER_DB', index=21, number=240001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_DB_SERVICE', index=22, number=240002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_DB_END', index=23, number=249999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_MSG_END', index=24, number=299999,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=31,
  serialized_end=705,
)
_sym_db.RegisterEnumDescriptor(_EMSSMSGID)

emSSMsgId = enum_type_wrapper.EnumTypeWrapper(_EMSSMSGID)
SVR_MSG_INVALID = 0
SVR_MSG_HEART_BEAT = 1
SVR_MSG_BEGIN = 200000
SVR_MSG_COMMON_PUSH_PLAYER_SVRID = 200001
SVR_MSG_COMMON_END = 200999
SVR_MSG_CLUSTER_BEGIN = 201000
SVR_MSG_REGISTER_CLUSTER = 201001
SVR_MSG_BROAD_CLUSTER = 201002
SVR_MSG_CLUSTER_END = 201999
SVR_MSG_GAME_BEGIN = 210000
SVR_MSG_REGISTER_GAME = 210001
SVR_MSG_GAME_LOGIN = 210002
SVR_MSG_GAME_END = 219999
SVR_MSG_WORLD_BEGIN = 220000
SVR_MSG_REGISTER_WORLD = 220001
SVR_MSG_WORLD_LOGIN = 220002
SVR_MSG_WORLD_END = 229999
SVR_MSG_LOGIN_BEGIN = 230000
SVR_MSG_REGISTER_LOGIN = 230001
SVR_MSG_LOGIN_END = 239999
SVR_MSG_DB_BEGIN = 240000
SVR_MSG_REGISTER_DB = 240001
SVR_MSG_DB_SERVICE = 240002
SVR_MSG_DB_END = 249999
SVR_MSG_END = 299999


DESCRIPTOR.enum_types_by_name['emSSMsgId'] = _EMSSMSGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
