# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock_code.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ret_base_pb2 as ret__base__pb2
import public_message_pb2 as public__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stock_code.proto',
  package='QuoteProto',
  syntax='proto2',
  serialized_pb=_b('\n\x10stock_code.proto\x12\nQuoteProto\x1a\x0eret_base.proto\x1a\x14public_message.proto\"+\n\x13GetStockCodeRequest\x12\x14\n\x0cmarkets_code\x18\x01 \x02(\t\"e\n\x14GetStockCodeResponse\x12\x1c\n\x03ret\x18\x01 \x02(\x0b\x32\x0f.QuoteProto.Ret\x12/\n\x0b\x63odes_table\x18\x03 \x03(\x0b\x32\x1a.QuoteProto.StockCodeTable')
  ,
  dependencies=[ret__base__pb2.DESCRIPTOR,public__message__pb2.DESCRIPTOR,])




_GETSTOCKCODEREQUEST = _descriptor.Descriptor(
  name='GetStockCodeRequest',
  full_name='QuoteProto.GetStockCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='markets_code', full_name='QuoteProto.GetStockCodeRequest.markets_code', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=113,
)


_GETSTOCKCODERESPONSE = _descriptor.Descriptor(
  name='GetStockCodeResponse',
  full_name='QuoteProto.GetStockCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='QuoteProto.GetStockCodeResponse.ret', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codes_table', full_name='QuoteProto.GetStockCodeResponse.codes_table', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=216,
)

_GETSTOCKCODERESPONSE.fields_by_name['ret'].message_type = ret__base__pb2._RET
_GETSTOCKCODERESPONSE.fields_by_name['codes_table'].message_type = public__message__pb2._STOCKCODETABLE
DESCRIPTOR.message_types_by_name['GetStockCodeRequest'] = _GETSTOCKCODEREQUEST
DESCRIPTOR.message_types_by_name['GetStockCodeResponse'] = _GETSTOCKCODERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetStockCodeRequest = _reflection.GeneratedProtocolMessageType('GetStockCodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSTOCKCODEREQUEST,
  __module__ = 'stock_code_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.GetStockCodeRequest)
  ))
_sym_db.RegisterMessage(GetStockCodeRequest)

GetStockCodeResponse = _reflection.GeneratedProtocolMessageType('GetStockCodeResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSTOCKCODERESPONSE,
  __module__ = 'stock_code_pb2'
  # @@protoc_insertion_point(class_scope:QuoteProto.GetStockCodeResponse)
  ))
_sym_db.RegisterMessage(GetStockCodeResponse)


# @@protoc_insertion_point(module_scope)
