# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: world.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cluster_pb2 as cluster__pb2
import base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='world.proto',
  package='ProtoMsg',
  syntax='proto3',
  serialized_pb=_b('\n\x0bworld.proto\x12\x08ProtoMsg\x1a\rcluster.proto\x1a\nbase.proto\"E\n\x18PbSvrRegisterWorldReqMsg\x12)\n\x08svr_info\x18\x01 \x01(\x0b\x32\x17.ProtoMsg.PbSvrBaseInfo\"6\n\x18PbSvrRegisterWorldResMsg\x12\x1a\n\x03ret\x18\x01 \x01(\x0b\x32\r.ProtoMsg.Ret\"4\n\x15PbSvrWorldLoginReqMsg\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12\x0e\n\x06online\x18\x02 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[cluster__pb2.DESCRIPTOR,base__pb2.DESCRIPTOR,])




_PBSVRREGISTERWORLDREQMSG = _descriptor.Descriptor(
  name='PbSvrRegisterWorldReqMsg',
  full_name='ProtoMsg.PbSvrRegisterWorldReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svr_info', full_name='ProtoMsg.PbSvrRegisterWorldReqMsg.svr_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=121,
)


_PBSVRREGISTERWORLDRESMSG = _descriptor.Descriptor(
  name='PbSvrRegisterWorldResMsg',
  full_name='ProtoMsg.PbSvrRegisterWorldResMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='ProtoMsg.PbSvrRegisterWorldResMsg.ret', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=177,
)


_PBSVRWORLDLOGINREQMSG = _descriptor.Descriptor(
  name='PbSvrWorldLoginReqMsg',
  full_name='ProtoMsg.PbSvrWorldLoginReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ProtoMsg.PbSvrWorldLoginReqMsg.uid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='online', full_name='ProtoMsg.PbSvrWorldLoginReqMsg.online', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=231,
)

_PBSVRREGISTERWORLDREQMSG.fields_by_name['svr_info'].message_type = cluster__pb2._PBSVRBASEINFO
_PBSVRREGISTERWORLDRESMSG.fields_by_name['ret'].message_type = base__pb2._RET
DESCRIPTOR.message_types_by_name['PbSvrRegisterWorldReqMsg'] = _PBSVRREGISTERWORLDREQMSG
DESCRIPTOR.message_types_by_name['PbSvrRegisterWorldResMsg'] = _PBSVRREGISTERWORLDRESMSG
DESCRIPTOR.message_types_by_name['PbSvrWorldLoginReqMsg'] = _PBSVRWORLDLOGINREQMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbSvrRegisterWorldReqMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterWorldReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERWORLDREQMSG,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterWorldReqMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterWorldReqMsg)

PbSvrRegisterWorldResMsg = _reflection.GeneratedProtocolMessageType('PbSvrRegisterWorldResMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRREGISTERWORLDRESMSG,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrRegisterWorldResMsg)
  ))
_sym_db.RegisterMessage(PbSvrRegisterWorldResMsg)

PbSvrWorldLoginReqMsg = _reflection.GeneratedProtocolMessageType('PbSvrWorldLoginReqMsg', (_message.Message,), dict(
  DESCRIPTOR = _PBSVRWORLDLOGINREQMSG,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMsg.PbSvrWorldLoginReqMsg)
  ))
_sym_db.RegisterMessage(PbSvrWorldLoginReqMsg)


# @@protoc_insertion_point(module_scope)
