// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package ProtoMsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EmSvrType int32

const (
	EmSvrType_ST_Invalid EmSvrType = 0
	EmSvrType_Gate       EmSvrType = 1
	EmSvrType_Gs         EmSvrType = 2
	EmSvrType_World      EmSvrType = 3
	EmSvrType_Login      EmSvrType = 4
	EmSvrType_Chat       EmSvrType = 5
	EmSvrType_DB         EmSvrType = 6
	EmSvrType_Cluster    EmSvrType = 7
)

var EmSvrType_name = map[int32]string{
	0: "ST_Invalid",
	1: "Gate",
	2: "Gs",
	3: "World",
	4: "Login",
	5: "Chat",
	6: "DB",
	7: "Cluster",
}
var EmSvrType_value = map[string]int32{
	"ST_Invalid": 0,
	"Gate":       1,
	"Gs":         2,
	"World":      3,
	"Login":      4,
	"Chat":       5,
	"DB":         6,
	"Cluster":    7,
}

func (x EmSvrType) String() string {
	return proto.EnumName(EmSvrType_name, int32(x))
}
func (EmSvrType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type EmClusterOprType int32

const (
	EmClusterOprType_COT_Invalid EmClusterOprType = 0
	EmClusterOprType_Add         EmClusterOprType = 1
	EmClusterOprType_Del         EmClusterOprType = 2
)

var EmClusterOprType_name = map[int32]string{
	0: "COT_Invalid",
	1: "Add",
	2: "Del",
}
var EmClusterOprType_value = map[string]int32{
	"COT_Invalid": 0,
	"Add":         1,
	"Del":         2,
}

func (x EmClusterOprType) String() string {
	return proto.EnumName(EmClusterOprType_name, int32(x))
}
func (EmClusterOprType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type PbSvrBaseInfo struct {
	GroupId    int32     `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	SvrId      int32     `protobuf:"varint,2,opt,name=svr_id,json=svrId" json:"svr_id,omitempty"`
	SvrType    EmSvrType `protobuf:"varint,3,opt,name=svr_type,json=svrType,enum=ProtoMsg.EmSvrType" json:"svr_type,omitempty"`
	Addr       string    `protobuf:"bytes,4,opt,name=addr" json:"addr,omitempty"`
	Ttl        int32     `protobuf:"varint,5,opt,name=ttl" json:"ttl,omitempty"`
	Timeout    int32     `protobuf:"varint,6,opt,name=timeout" json:"timeout,omitempty"`
	CsMsgBegin EmCSMsgId `protobuf:"varint,7,opt,name=cs_msg_begin,json=csMsgBegin,enum=ProtoMsg.EmCSMsgId" json:"cs_msg_begin,omitempty"`
	CsMsgEnd   EmCSMsgId `protobuf:"varint,8,opt,name=cs_msg_end,json=csMsgEnd,enum=ProtoMsg.EmCSMsgId" json:"cs_msg_end,omitempty"`
	SsMsgBegin EmSSMsgId `protobuf:"varint,9,opt,name=ss_msg_begin,json=ssMsgBegin,enum=ProtoMsg.EmSSMsgId" json:"ss_msg_begin,omitempty"`
	SsMsgEnd   EmSSMsgId `protobuf:"varint,10,opt,name=ss_msg_end,json=ssMsgEnd,enum=ProtoMsg.EmSSMsgId" json:"ss_msg_end,omitempty"`
}

func (m *PbSvrBaseInfo) Reset()                    { *m = PbSvrBaseInfo{} }
func (m *PbSvrBaseInfo) String() string            { return proto.CompactTextString(m) }
func (*PbSvrBaseInfo) ProtoMessage()               {}
func (*PbSvrBaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *PbSvrBaseInfo) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *PbSvrBaseInfo) GetSvrId() int32 {
	if m != nil {
		return m.SvrId
	}
	return 0
}

func (m *PbSvrBaseInfo) GetSvrType() EmSvrType {
	if m != nil {
		return m.SvrType
	}
	return EmSvrType_ST_Invalid
}

func (m *PbSvrBaseInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *PbSvrBaseInfo) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *PbSvrBaseInfo) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *PbSvrBaseInfo) GetCsMsgBegin() EmCSMsgId {
	if m != nil {
		return m.CsMsgBegin
	}
	return EmCSMsgId_CS_MSG_INVALID
}

func (m *PbSvrBaseInfo) GetCsMsgEnd() EmCSMsgId {
	if m != nil {
		return m.CsMsgEnd
	}
	return EmCSMsgId_CS_MSG_INVALID
}

func (m *PbSvrBaseInfo) GetSsMsgBegin() EmSSMsgId {
	if m != nil {
		return m.SsMsgBegin
	}
	return EmSSMsgId_SVR_MSG_INVALID
}

func (m *PbSvrBaseInfo) GetSsMsgEnd() EmSSMsgId {
	if m != nil {
		return m.SsMsgEnd
	}
	return EmSSMsgId_SVR_MSG_INVALID
}

// SVR_MSG_REGISTER_CLUSTER
type PbSvrRegisterClusterReqMsg struct {
	SvrInfo  *PbSvrBaseInfo `protobuf:"bytes,1,opt,name=svr_info,json=svrInfo" json:"svr_info,omitempty"`
	SvrTypes []EmSvrType    `protobuf:"varint,2,rep,packed,name=svr_types,json=svrTypes,enum=ProtoMsg.EmSvrType" json:"svr_types,omitempty"`
}

func (m *PbSvrRegisterClusterReqMsg) Reset()                    { *m = PbSvrRegisterClusterReqMsg{} }
func (m *PbSvrRegisterClusterReqMsg) String() string            { return proto.CompactTextString(m) }
func (*PbSvrRegisterClusterReqMsg) ProtoMessage()               {}
func (*PbSvrRegisterClusterReqMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PbSvrRegisterClusterReqMsg) GetSvrInfo() *PbSvrBaseInfo {
	if m != nil {
		return m.SvrInfo
	}
	return nil
}

func (m *PbSvrRegisterClusterReqMsg) GetSvrTypes() []EmSvrType {
	if m != nil {
		return m.SvrTypes
	}
	return nil
}

type PbSvrRegisterClusterResMsg struct {
	Ret  *Ret             `protobuf:"bytes,1,opt,name=ret" json:"ret,omitempty"`
	Svrs []*PbSvrBaseInfo `protobuf:"bytes,2,rep,name=svrs" json:"svrs,omitempty"`
}

func (m *PbSvrRegisterClusterResMsg) Reset()                    { *m = PbSvrRegisterClusterResMsg{} }
func (m *PbSvrRegisterClusterResMsg) String() string            { return proto.CompactTextString(m) }
func (*PbSvrRegisterClusterResMsg) ProtoMessage()               {}
func (*PbSvrRegisterClusterResMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *PbSvrRegisterClusterResMsg) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *PbSvrRegisterClusterResMsg) GetSvrs() []*PbSvrBaseInfo {
	if m != nil {
		return m.Svrs
	}
	return nil
}

// SVR_MSG_BROAD_CLUSTER
type PbSvrBroadClusterMsg struct {
	OprType EmClusterOprType `protobuf:"varint,1,opt,name=opr_type,json=oprType,enum=ProtoMsg.EmClusterOprType" json:"opr_type,omitempty"`
	SvrInfo *PbSvrBaseInfo   `protobuf:"bytes,2,opt,name=svr_info,json=svrInfo" json:"svr_info,omitempty"`
}

func (m *PbSvrBroadClusterMsg) Reset()                    { *m = PbSvrBroadClusterMsg{} }
func (m *PbSvrBroadClusterMsg) String() string            { return proto.CompactTextString(m) }
func (*PbSvrBroadClusterMsg) ProtoMessage()               {}
func (*PbSvrBroadClusterMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *PbSvrBroadClusterMsg) GetOprType() EmClusterOprType {
	if m != nil {
		return m.OprType
	}
	return EmClusterOprType_COT_Invalid
}

func (m *PbSvrBroadClusterMsg) GetSvrInfo() *PbSvrBaseInfo {
	if m != nil {
		return m.SvrInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*PbSvrBaseInfo)(nil), "ProtoMsg.PbSvrBaseInfo")
	proto.RegisterType((*PbSvrRegisterClusterReqMsg)(nil), "ProtoMsg.PbSvrRegisterClusterReqMsg")
	proto.RegisterType((*PbSvrRegisterClusterResMsg)(nil), "ProtoMsg.PbSvrRegisterClusterResMsg")
	proto.RegisterType((*PbSvrBroadClusterMsg)(nil), "ProtoMsg.PbSvrBroadClusterMsg")
	proto.RegisterEnum("ProtoMsg.EmSvrType", EmSvrType_name, EmSvrType_value)
	proto.RegisterEnum("ProtoMsg.EmClusterOprType", EmClusterOprType_name, EmClusterOprType_value)
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x8e, 0xd2, 0x40,
	0x14, 0xb5, 0x2d, 0xd0, 0xf6, 0x22, 0xeb, 0x64, 0xd4, 0x58, 0x79, 0x91, 0xf0, 0x44, 0xd6, 0x84,
	0x28, 0x86, 0x0f, 0x10, 0xd6, 0x6c, 0x9a, 0x48, 0x76, 0x53, 0x36, 0xf1, 0xb1, 0x69, 0x99, 0xd9,
	0x5a, 0x53, 0x3a, 0x75, 0xee, 0xd0, 0x64, 0x1f, 0x35, 0xf1, 0xbf, 0xcd, 0x4c, 0x8b, 0x2c, 0xab,
	0x98, 0x7d, 0xe2, 0xcc, 0x9d, 0x7b, 0xef, 0x39, 0x9c, 0x33, 0x85, 0xc1, 0xa6, 0xd8, 0xa1, 0xe2,
	0x72, 0x5a, 0x49, 0xa1, 0x04, 0xf5, 0xae, 0xf5, 0xcf, 0x0a, 0xb3, 0x21, 0xa4, 0x09, 0xf2, 0xa6,
	0x3a, 0x24, 0x1b, 0x8c, 0x0d, 0xca, 0xd9, 0xbe, 0x82, 0x0f, 0x2a, 0xe3, 0x5f, 0x0e, 0x0c, 0xae,
	0xd3, 0x75, 0x2d, 0x17, 0x09, 0xf2, 0xb0, 0xbc, 0x15, 0xf4, 0x35, 0x78, 0x99, 0x14, 0xbb, 0x2a,
	0xce, 0x59, 0x60, 0x8d, 0xac, 0x49, 0x37, 0x72, 0xcd, 0x39, 0x64, 0xf4, 0x25, 0xf4, 0xb0, 0x96,
	0xfa, 0xc2, 0x36, 0x17, 0x5d, 0xac, 0x65, 0xc8, 0xe8, 0x14, 0x3c, 0x5d, 0x56, 0x77, 0x15, 0x0f,
	0x9c, 0x91, 0x35, 0x39, 0x9b, 0x3d, 0x9f, 0xee, 0x05, 0x4d, 0xf9, 0x76, 0x5d, 0xcb, 0x9b, 0xbb,
	0x8a, 0x47, 0x2e, 0x36, 0x80, 0x52, 0xe8, 0x24, 0x8c, 0xc9, 0xa0, 0x33, 0xb2, 0x26, 0x7e, 0x64,
	0x30, 0x25, 0xe0, 0x28, 0x55, 0x04, 0x5d, 0xb3, 0x57, 0x43, 0x1a, 0x80, 0xab, 0xf2, 0x2d, 0x17,
	0x3b, 0x15, 0xf4, 0x1a, 0x19, 0xed, 0x91, 0xce, 0xe1, 0xe9, 0x06, 0xe3, 0x2d, 0x66, 0x71, 0xca,
	0xb3, 0xbc, 0x0c, 0xdc, 0xbf, 0x39, 0x97, 0xeb, 0x15, 0x66, 0x21, 0x8b, 0x60, 0x83, 0x2b, 0xcc,
	0x16, 0xba, 0x8d, 0xbe, 0x07, 0x68, 0xc7, 0x78, 0xc9, 0x02, 0xef, 0xf4, 0x90, 0x67, 0x86, 0x3e,
	0x95, 0x4c, 0x33, 0xe1, 0x7d, 0x26, 0xff, 0x1f, 0xff, 0x6e, 0xcf, 0x84, 0x47, 0x4c, 0x78, 0x60,
	0x82, 0xd3, 0x43, 0x1e, 0xb6, 0x4c, 0xe3, 0x9f, 0x16, 0x0c, 0x4d, 0x0e, 0x11, 0xcf, 0x72, 0x9d,
	0xec, 0xb2, 0x09, 0x38, 0xe2, 0xdf, 0x57, 0x98, 0xd1, 0x59, 0x63, 0x71, 0x5e, 0xde, 0x0a, 0x13,
	0x4a, 0x7f, 0xf6, 0xea, 0xb0, 0xef, 0x28, 0x3f, 0x63, 0xb3, 0x09, 0xf2, 0x1d, 0xf8, 0xfb, 0x58,
	0x30, 0xb0, 0x47, 0xce, 0xa9, 0x5c, 0xbc, 0x36, 0x17, 0x1c, 0x7f, 0x3b, 0xa5, 0x41, 0xab, 0xa4,
	0x6f, 0xc0, 0x91, 0x5c, 0xb5, 0xf4, 0x83, 0xc3, 0xa6, 0x88, 0xab, 0x48, 0xdf, 0xd0, 0xb7, 0xd0,
	0xc1, 0x5a, 0x36, 0x5c, 0xff, 0x11, 0x68, 0x9a, 0xc6, 0x3f, 0x2c, 0x78, 0xd1, 0xd4, 0xa5, 0x48,
	0x58, 0xcb, 0xa4, 0x69, 0xe6, 0xe0, 0x89, 0xaa, 0x7d, 0x4d, 0x96, 0xb1, 0x6e, 0x78, 0x14, 0x52,
	0xd3, 0x79, 0x55, 0xb5, 0x8f, 0x4a, 0x34, 0xe0, 0xc8, 0x21, 0xfb, 0x71, 0x0e, 0x9d, 0xa7, 0xe0,
	0xff, 0xb1, 0x81, 0x9e, 0x01, 0xac, 0x6f, 0xe2, 0xb0, 0xac, 0x93, 0x22, 0x67, 0xe4, 0x09, 0xf5,
	0xa0, 0x73, 0x99, 0x28, 0x4e, 0x2c, 0xda, 0x03, 0xfb, 0x12, 0x89, 0x4d, 0x7d, 0xe8, 0x7e, 0x11,
	0xb2, 0x60, 0xc4, 0xd1, 0xf0, 0xb3, 0xc8, 0xf2, 0x92, 0x74, 0x74, 0xdf, 0xf2, 0x6b, 0xa2, 0x48,
	0x57, 0xf7, 0x5d, 0x2c, 0x48, 0x8f, 0xf6, 0xc1, 0x6d, 0x55, 0x12, 0xf7, 0x7c, 0x0e, 0xe4, 0xa1,
	0x68, 0xfa, 0x0c, 0xfa, 0xcb, 0xab, 0xfb, 0x5c, 0x2e, 0x38, 0x1f, 0x19, 0x23, 0x96, 0x06, 0x17,
	0xbc, 0x20, 0x76, 0xda, 0x33, 0x9f, 0xe7, 0x87, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xec, 0xd1,
	0x80, 0x49, 0xe9, 0x03, 0x00, 0x00,
}
