// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package ProtoMsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EmDBEngin int32

const (
	EmDBEngin_DB_engine_invalid EmDBEngin = 0
	EmDBEngin_DB_engine_redis   EmDBEngin = 1
	EmDBEngin_DB_engine_mysql   EmDBEngin = 2
)

var EmDBEngin_name = map[int32]string{
	0: "DB_engine_invalid",
	1: "DB_engine_redis",
	2: "DB_engine_mysql",
}
var EmDBEngin_value = map[string]int32{
	"DB_engine_invalid": 0,
	"DB_engine_redis":   1,
	"DB_engine_mysql":   2,
}

func (x EmDBEngin) String() string {
	return proto.EnumName(EmDBEngin_name, int32(x))
}
func (EmDBEngin) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type PbSvrDBServiceReqMsg struct {
	DbEngine   EmDBEngin `protobuf:"varint,1,opt,name=db_engine,json=dbEngine,enum=ProtoMsg.EmDBEngin" json:"db_engine,omitempty"`
	ReqMsgName string    `protobuf:"bytes,2,opt,name=req_msg_name,json=reqMsgName" json:"req_msg_name,omitempty"`
	ReqData    string    `protobuf:"bytes,3,opt,name=req_data,json=reqData" json:"req_data,omitempty"`
}

func (m *PbSvrDBServiceReqMsg) Reset()                    { *m = PbSvrDBServiceReqMsg{} }
func (m *PbSvrDBServiceReqMsg) String() string            { return proto.CompactTextString(m) }
func (*PbSvrDBServiceReqMsg) ProtoMessage()               {}
func (*PbSvrDBServiceReqMsg) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *PbSvrDBServiceReqMsg) GetDbEngine() EmDBEngin {
	if m != nil {
		return m.DbEngine
	}
	return EmDBEngin_DB_engine_invalid
}

func (m *PbSvrDBServiceReqMsg) GetReqMsgName() string {
	if m != nil {
		return m.ReqMsgName
	}
	return ""
}

func (m *PbSvrDBServiceReqMsg) GetReqData() string {
	if m != nil {
		return m.ReqData
	}
	return ""
}

type PbSvrDBServiceResMsg struct {
	Ret        *Ret      `protobuf:"bytes,1,opt,name=ret" json:"ret,omitempty"`
	DbEngine   EmDBEngin `protobuf:"varint,2,opt,name=db_engine,json=dbEngine,enum=ProtoMsg.EmDBEngin" json:"db_engine,omitempty"`
	ResMsgName string    `protobuf:"bytes,3,opt,name=res_msg_name,json=resMsgName" json:"res_msg_name,omitempty"`
	ResData    string    `protobuf:"bytes,4,opt,name=res_data,json=resData" json:"res_data,omitempty"`
}

func (m *PbSvrDBServiceResMsg) Reset()                    { *m = PbSvrDBServiceResMsg{} }
func (m *PbSvrDBServiceResMsg) String() string            { return proto.CompactTextString(m) }
func (*PbSvrDBServiceResMsg) ProtoMessage()               {}
func (*PbSvrDBServiceResMsg) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *PbSvrDBServiceResMsg) GetRet() *Ret {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *PbSvrDBServiceResMsg) GetDbEngine() EmDBEngin {
	if m != nil {
		return m.DbEngine
	}
	return EmDBEngin_DB_engine_invalid
}

func (m *PbSvrDBServiceResMsg) GetResMsgName() string {
	if m != nil {
		return m.ResMsgName
	}
	return ""
}

func (m *PbSvrDBServiceResMsg) GetResData() string {
	if m != nil {
		return m.ResData
	}
	return ""
}

type PbSvrDBTestRecvReqMsg struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *PbSvrDBTestRecvReqMsg) Reset()                    { *m = PbSvrDBTestRecvReqMsg{} }
func (m *PbSvrDBTestRecvReqMsg) String() string            { return proto.CompactTextString(m) }
func (*PbSvrDBTestRecvReqMsg) ProtoMessage()               {}
func (*PbSvrDBTestRecvReqMsg) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *PbSvrDBTestRecvReqMsg) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PbSvrDBTestRecvReqMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PbSvrDBTestRecvResMsg struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *PbSvrDBTestRecvResMsg) Reset()                    { *m = PbSvrDBTestRecvResMsg{} }
func (m *PbSvrDBTestRecvResMsg) String() string            { return proto.CompactTextString(m) }
func (*PbSvrDBTestRecvResMsg) ProtoMessage()               {}
func (*PbSvrDBTestRecvResMsg) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *PbSvrDBTestRecvResMsg) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PbSvrDBTestRecvResMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*PbSvrDBServiceReqMsg)(nil), "ProtoMsg.PbSvrDBServiceReqMsg")
	proto.RegisterType((*PbSvrDBServiceResMsg)(nil), "ProtoMsg.PbSvrDBServiceResMsg")
	proto.RegisterType((*PbSvrDBTestRecvReqMsg)(nil), "ProtoMsg.PbSvrDBTestRecvReqMsg")
	proto.RegisterType((*PbSvrDBTestRecvResMsg)(nil), "ProtoMsg.PbSvrDBTestRecvResMsg")
	proto.RegisterEnum("ProtoMsg.EmDBEngin", EmDBEngin_name, EmDBEngin_value)
}

func init() { proto.RegisterFile("db.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd1, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0x07, 0xf0, 0xaf, 0x85, 0x4f, 0xcb, 0x28, 0x88, 0x8b, 0x24, 0xc8, 0x45, 0xc2, 0x89, 0x78,
	0x20, 0x06, 0x8f, 0xde, 0x48, 0xbd, 0x89, 0x21, 0x8b, 0xf7, 0x66, 0x97, 0x9d, 0x34, 0x9b, 0xd0,
	0x62, 0x77, 0xd6, 0x26, 0x3e, 0x80, 0xaf, 0xe2, 0x73, 0x9a, 0x2e, 0xad, 0xb5, 0x09, 0x07, 0x4e,
	0x9d, 0xec, 0xbf, 0x3b, 0xf9, 0xcd, 0x2c, 0x04, 0x4a, 0xce, 0xdf, 0xcd, 0xde, 0xee, 0x59, 0xb0,
	0x2e, 0x3e, 0x2b, 0x8a, 0xc7, 0xdd, 0xed, 0xee, 0x83, 0x2c, 0x9a, 0x43, 0x30, 0x06, 0x29, 0x08,
	0x0f, 0xf5, 0xf4, 0xcb, 0x83, 0x9b, 0xb5, 0xdc, 0xe4, 0x26, 0x5c, 0x6e, 0xd0, 0xe4, 0x7a, 0x8b,
	0x1c, 0xb3, 0x15, 0xc5, 0xec, 0x01, 0x3a, 0x4a, 0x46, 0x98, 0xc6, 0x3a, 0xc5, 0x91, 0x37, 0xf1,
	0x66, 0xbd, 0xc5, 0x60, 0x5e, 0x75, 0x9c, 0x63, 0x12, 0x2e, 0x9f, 0x8b, 0x8c, 0x07, 0x4a, 0xba,
	0x02, 0xd9, 0x04, 0x2e, 0x0d, 0x66, 0x51, 0x42, 0x71, 0x94, 0x8a, 0x04, 0x47, 0xfe, 0xc4, 0x9b,
	0x75, 0x38, 0x18, 0xd7, 0xef, 0x55, 0x24, 0xc8, 0x6e, 0x21, 0x28, 0xfe, 0x50, 0xc2, 0x8a, 0x51,
	0xcb, 0xa5, 0xe7, 0x06, 0xb3, 0x50, 0x58, 0x31, 0xfd, 0x3e, 0xe2, 0xa0, 0xc2, 0x71, 0x07, 0x2d,
	0x83, 0xd6, 0x09, 0x2e, 0x16, 0xdd, 0x5a, 0xc0, 0xd1, 0xf2, 0x22, 0x69, 0x42, 0xfd, 0x93, 0xa1,
	0x54, 0x43, 0x5b, 0x15, 0x94, 0x1a, 0x50, 0x3a, 0x40, 0xdb, 0x15, 0x94, 0x1c, 0xf4, 0x09, 0x86,
	0xa5, 0xf3, 0x0d, 0xc9, 0x72, 0xdc, 0xe6, 0xe5, 0xc2, 0x7a, 0xe0, 0x6b, 0xe5, 0x9c, 0xff, 0xb9,
	0xaf, 0x15, 0x63, 0xd0, 0xfe, 0xb3, 0x06, 0x57, 0x1f, 0xbd, 0x4c, 0x27, 0x5e, 0xbe, 0x7f, 0x81,
	0xce, 0xef, 0x34, 0x6c, 0x08, 0xd7, 0xe1, 0xb2, 0x9c, 0x3a, 0xd2, 0x69, 0x2e, 0x76, 0x5a, 0xf5,
	0xff, 0xb1, 0x01, 0x5c, 0xd5, 0xc7, 0x06, 0x95, 0xa6, 0xbe, 0xd7, 0x3c, 0x4c, 0x3e, 0x29, 0xdb,
	0xf5, 0x7d, 0x79, 0xe6, 0xde, 0xff, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x8e, 0xc8, 0x18,
	0x30, 0x02, 0x00, 0x00,
}
